// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: archive_files.sql

package sqlc

import (
	"context"
)

const createArchiveFile = `-- name: CreateArchiveFile :one
INSERT INTO
    archive_files (
        run_id,
        archive_path,
        file_type,
        media_type,
        size_bytes,
        sha256,
        is_public
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7
    )
RETURNING
    id, run_id, archive_path, file_type, media_type, size_bytes, sha256, is_public
`

type CreateArchiveFileParams struct {
	RunID       int64  `json:"run_id"`
	ArchivePath string `json:"archive_path"`
	FileType    string `json:"file_type"`
	MediaType   string `json:"media_type"`
	SizeBytes   int64  `json:"size_bytes"`
	Sha256      string `json:"sha256"`
	IsPublic    int64  `json:"is_public"`
}

func (q *Queries) CreateArchiveFile(ctx context.Context, arg CreateArchiveFileParams) (ArchiveFile, error) {
	row := q.db.QueryRowContext(ctx, createArchiveFile,
		arg.RunID,
		arg.ArchivePath,
		arg.FileType,
		arg.MediaType,
		arg.SizeBytes,
		arg.Sha256,
		arg.IsPublic,
	)
	var i ArchiveFile
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ArchivePath,
		&i.FileType,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.IsPublic,
	)
	return i, err
}

const getArchiveFileByID = `-- name: GetArchiveFileByID :one
SELECT
    af.id, af.run_id, af.archive_path, af.file_type, af.media_type, af.size_bytes, af.sha256, af.is_public,
    r.run_uid,
    a.relative_path AS archive_relative_path
FROM
    archive_files af
    JOIN runs r ON r.id = af.run_id
    JOIN archives a ON a.id = r.archive_id
WHERE
    af.id = ?1
LIMIT
    1
`

type GetArchiveFileByIDRow struct {
	ID                  int64  `json:"id"`
	RunID               int64  `json:"run_id"`
	ArchivePath         string `json:"archive_path"`
	FileType            string `json:"file_type"`
	MediaType           string `json:"media_type"`
	SizeBytes           int64  `json:"size_bytes"`
	Sha256              string `json:"sha256"`
	IsPublic            int64  `json:"is_public"`
	RunUid              string `json:"run_uid"`
	ArchiveRelativePath string `json:"archive_relative_path"`
}

func (q *Queries) GetArchiveFileByID(ctx context.Context, id int64) (GetArchiveFileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getArchiveFileByID, id)
	var i GetArchiveFileByIDRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ArchivePath,
		&i.FileType,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.IsPublic,
		&i.RunUid,
		&i.ArchiveRelativePath,
	)
	return i, err
}

const getPublicArchiveFileByID = `-- name: GetPublicArchiveFileByID :one
SELECT
    af.id, af.run_id, af.archive_path, af.file_type, af.media_type, af.size_bytes, af.sha256, af.is_public,
    r.run_uid,
    a.relative_path AS archive_relative_path
FROM
    archive_files af
    JOIN runs r ON r.id = af.run_id
    JOIN archives a ON a.id = r.archive_id
WHERE
    af.id = ?1
    AND af.is_public = 1
LIMIT
    1
`

type GetPublicArchiveFileByIDRow struct {
	ID                  int64  `json:"id"`
	RunID               int64  `json:"run_id"`
	ArchivePath         string `json:"archive_path"`
	FileType            string `json:"file_type"`
	MediaType           string `json:"media_type"`
	SizeBytes           int64  `json:"size_bytes"`
	Sha256              string `json:"sha256"`
	IsPublic            int64  `json:"is_public"`
	RunUid              string `json:"run_uid"`
	ArchiveRelativePath string `json:"archive_relative_path"`
}

// Use this for the public artifact endpoint.
// It guarantees the returned entry is marked public.
func (q *Queries) GetPublicArchiveFileByID(ctx context.Context, id int64) (GetPublicArchiveFileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPublicArchiveFileByID, id)
	var i GetPublicArchiveFileByIDRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ArchivePath,
		&i.FileType,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.IsPublic,
		&i.RunUid,
		&i.ArchiveRelativePath,
	)
	return i, err
}

const listArchiveFilesForRun = `-- name: ListArchiveFilesForRun :many
SELECT
    id, run_id, archive_path, file_type, media_type, size_bytes, sha256, is_public
FROM
    archive_files
WHERE
    run_id = ?1
ORDER BY
    archive_path
`

func (q *Queries) ListArchiveFilesForRun(ctx context.Context, runID int64) ([]ArchiveFile, error) {
	rows, err := q.db.QueryContext(ctx, listArchiveFilesForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchiveFile{}
	for rows.Next() {
		var i ArchiveFile
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ArchivePath,
			&i.FileType,
			&i.MediaType,
			&i.SizeBytes,
			&i.Sha256,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicArchiveFilesForRun = `-- name: ListPublicArchiveFilesForRun :many
SELECT
    id, run_id, archive_path, file_type, media_type, size_bytes, sha256, is_public
FROM
    archive_files
WHERE
    run_id = ?1
    AND is_public = 1
ORDER BY
    archive_path
`

func (q *Queries) ListPublicArchiveFilesForRun(ctx context.Context, runID int64) ([]ArchiveFile, error) {
	rows, err := q.db.QueryContext(ctx, listPublicArchiveFilesForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchiveFile{}
	for rows.Next() {
		var i ArchiveFile
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ArchivePath,
			&i.FileType,
			&i.MediaType,
			&i.SizeBytes,
			&i.Sha256,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArchiveFile = `-- name: UpsertArchiveFile :one
INSERT INTO
    archive_files (
        run_id,
        archive_path,
        file_type,
        media_type,
        size_bytes,
        sha256,
        is_public
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7
    ) ON CONFLICT(run_id, archive_path) DO
UPDATE
SET
    file_type = excluded.file_type,
    media_type = excluded.media_type,
    size_bytes = excluded.size_bytes,
    sha256 = excluded.sha256,
    is_public = excluded.is_public
RETURNING
    id, run_id, archive_path, file_type, media_type, size_bytes, sha256, is_public
`

type UpsertArchiveFileParams struct {
	RunID       int64  `json:"run_id"`
	ArchivePath string `json:"archive_path"`
	FileType    string `json:"file_type"`
	MediaType   string `json:"media_type"`
	SizeBytes   int64  `json:"size_bytes"`
	Sha256      string `json:"sha256"`
	IsPublic    int64  `json:"is_public"`
}

func (q *Queries) UpsertArchiveFile(ctx context.Context, arg UpsertArchiveFileParams) (ArchiveFile, error) {
	row := q.db.QueryRowContext(ctx, upsertArchiveFile,
		arg.RunID,
		arg.ArchivePath,
		arg.FileType,
		arg.MediaType,
		arg.SizeBytes,
		arg.Sha256,
		arg.IsPublic,
	)
	var i ArchiveFile
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ArchivePath,
		&i.FileType,
		&i.MediaType,
		&i.SizeBytes,
		&i.Sha256,
		&i.IsPublic,
	)
	return i, err
}
