// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: archives.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countArchivesByImportStatus = `-- name: CountArchivesByImportStatus :many
SELECT
    import_status,
    COUNT(*) AS archive_count
FROM
    archives
GROUP BY
    import_status
ORDER BY
    import_status
`

type CountArchivesByImportStatusRow struct {
	ImportStatus string `json:"import_status"`
	ArchiveCount int64  `json:"archive_count"`
}

func (q *Queries) CountArchivesByImportStatus(ctx context.Context) ([]CountArchivesByImportStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countArchivesByImportStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountArchivesByImportStatusRow{}
	for rows.Next() {
		var i CountArchivesByImportStatusRow
		if err := rows.Scan(&i.ImportStatus, &i.ArchiveCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createArchive = `-- name: CreateArchive :one
INSERT INTO
    archives (
        relative_path,
        file_size_bytes,
        file_mtime_ns,
        archive_sha256,
        import_status
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        'discovered'
    )
RETURNING
    id, relative_path, file_size_bytes, file_mtime_ns, archive_sha256, import_status, import_attempts, import_error, discovered_at, import_started_at, imported_at
`

type CreateArchiveParams struct {
	RelativePath  string         `json:"relative_path"`
	FileSizeBytes int64          `json:"file_size_bytes"`
	FileMtimeNs   sql.NullInt64  `json:"file_mtime_ns"`
	ArchiveSha256 sql.NullString `json:"archive_sha256"`
}

func (q *Queries) CreateArchive(ctx context.Context, arg CreateArchiveParams) (Archive, error) {
	row := q.db.QueryRowContext(ctx, createArchive,
		arg.RelativePath,
		arg.FileSizeBytes,
		arg.FileMtimeNs,
		arg.ArchiveSha256,
	)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.RelativePath,
		&i.FileSizeBytes,
		&i.FileMtimeNs,
		&i.ArchiveSha256,
		&i.ImportStatus,
		&i.ImportAttempts,
		&i.ImportError,
		&i.DiscoveredAt,
		&i.ImportStartedAt,
		&i.ImportedAt,
	)
	return i, err
}

const createImportingArchive = `-- name: CreateImportingArchive :one
INSERT INTO
    archives (
        relative_path,
        file_size_bytes,
        file_mtime_ns,
        archive_sha256,
        import_status,
        import_attempts,
        import_started_at
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        'importing',
        1,
        strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
    )
RETURNING
    id, relative_path, file_size_bytes, file_mtime_ns, archive_sha256, import_status, import_attempts, import_error, discovered_at, import_started_at, imported_at
`

type CreateImportingArchiveParams struct {
	RelativePath  string         `json:"relative_path"`
	FileSizeBytes int64          `json:"file_size_bytes"`
	FileMtimeNs   sql.NullInt64  `json:"file_mtime_ns"`
	ArchiveSha256 sql.NullString `json:"archive_sha256"`
}

func (q *Queries) CreateImportingArchive(ctx context.Context, arg CreateImportingArchiveParams) (Archive, error) {
	row := q.db.QueryRowContext(ctx, createImportingArchive,
		arg.RelativePath,
		arg.FileSizeBytes,
		arg.FileMtimeNs,
		arg.ArchiveSha256,
	)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.RelativePath,
		&i.FileSizeBytes,
		&i.FileMtimeNs,
		&i.ArchiveSha256,
		&i.ImportStatus,
		&i.ImportAttempts,
		&i.ImportError,
		&i.DiscoveredAt,
		&i.ImportStartedAt,
		&i.ImportedAt,
	)
	return i, err
}

const getArchiveByID = `-- name: GetArchiveByID :one
SELECT
    id, relative_path, file_size_bytes, file_mtime_ns, archive_sha256, import_status, import_attempts, import_error, discovered_at, import_started_at, imported_at
FROM
    archives
WHERE
    id = ?1
LIMIT
    1
`

func (q *Queries) GetArchiveByID(ctx context.Context, id int64) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getArchiveByID, id)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.RelativePath,
		&i.FileSizeBytes,
		&i.FileMtimeNs,
		&i.ArchiveSha256,
		&i.ImportStatus,
		&i.ImportAttempts,
		&i.ImportError,
		&i.DiscoveredAt,
		&i.ImportStartedAt,
		&i.ImportedAt,
	)
	return i, err
}

const getArchiveByPath = `-- name: GetArchiveByPath :one
SELECT
    id, relative_path, file_size_bytes, file_mtime_ns, archive_sha256, import_status, import_attempts, import_error, discovered_at, import_started_at, imported_at
FROM
    archives
WHERE
    relative_path = ?1
LIMIT
    1
`

func (q *Queries) GetArchiveByPath(ctx context.Context, relativePath string) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getArchiveByPath, relativePath)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.RelativePath,
		&i.FileSizeBytes,
		&i.FileMtimeNs,
		&i.ArchiveSha256,
		&i.ImportStatus,
		&i.ImportAttempts,
		&i.ImportError,
		&i.DiscoveredAt,
		&i.ImportStartedAt,
		&i.ImportedAt,
	)
	return i, err
}

const listArchivesPendingImport = `-- name: ListArchivesPendingImport :many
SELECT
    id, relative_path, file_size_bytes, file_mtime_ns, archive_sha256, import_status, import_attempts, import_error, discovered_at, import_started_at, imported_at
FROM
    archives
WHERE
    import_status IN ('discovered', 'failed')
ORDER BY
    discovered_at ASC
LIMIT
    ?1
`

func (q *Queries) ListArchivesPendingImport(ctx context.Context, resultLimit int64) ([]Archive, error) {
	rows, err := q.db.QueryContext(ctx, listArchivesPendingImport, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Archive{}
	for rows.Next() {
		var i Archive
		if err := rows.Scan(
			&i.ID,
			&i.RelativePath,
			&i.FileSizeBytes,
			&i.FileMtimeNs,
			&i.ArchiveSha256,
			&i.ImportStatus,
			&i.ImportAttempts,
			&i.ImportError,
			&i.DiscoveredAt,
			&i.ImportStartedAt,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedArchives = `-- name: ListFailedArchives :many
SELECT
    id, relative_path, file_size_bytes, file_mtime_ns, archive_sha256, import_status, import_attempts, import_error, discovered_at, import_started_at, imported_at
FROM
    archives
WHERE
    import_status = 'failed'
ORDER BY
    discovered_at DESC
LIMIT
    ?1
`

func (q *Queries) ListFailedArchives(ctx context.Context, resultLimit int64) ([]Archive, error) {
	rows, err := q.db.QueryContext(ctx, listFailedArchives, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Archive{}
	for rows.Next() {
		var i Archive
		if err := rows.Scan(
			&i.ID,
			&i.RelativePath,
			&i.FileSizeBytes,
			&i.FileMtimeNs,
			&i.ArchiveSha256,
			&i.ImportStatus,
			&i.ImportAttempts,
			&i.ImportError,
			&i.DiscoveredAt,
			&i.ImportStartedAt,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArchiveFailed = `-- name: MarkArchiveFailed :exec
UPDATE
    archives
SET
    import_status = 'failed',
    import_error = ?1
WHERE
    id = ?2
`

type MarkArchiveFailedParams struct {
	ImportError sql.NullString `json:"import_error"`
	ID          int64          `json:"id"`
}

func (q *Queries) MarkArchiveFailed(ctx context.Context, arg MarkArchiveFailedParams) error {
	_, err := q.db.ExecContext(ctx, markArchiveFailed, arg.ImportError, arg.ID)
	return err
}

const markArchiveIgnored = `-- name: MarkArchiveIgnored :exec
UPDATE
    archives
SET
    import_status = 'ignored',
    import_error = ?1
WHERE
    id = ?2
`

type MarkArchiveIgnoredParams struct {
	Reason sql.NullString `json:"reason"`
	ID     int64          `json:"id"`
}

func (q *Queries) MarkArchiveIgnored(ctx context.Context, arg MarkArchiveIgnoredParams) error {
	_, err := q.db.ExecContext(ctx, markArchiveIgnored, arg.Reason, arg.ID)
	return err
}

const markArchiveImported = `-- name: MarkArchiveImported :exec
UPDATE
    archives
SET
    import_status = 'imported',
    imported_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    import_error = NULL
WHERE
    id = ?1
`

func (q *Queries) MarkArchiveImported(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markArchiveImported, id)
	return err
}

const markArchiveImporting = `-- name: MarkArchiveImporting :one
UPDATE
    archives
SET
    import_status = 'importing',
    import_started_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
    import_attempts = import_attempts + 1,
    import_error = NULL
WHERE
    id = ?1
    AND import_status IN ('discovered', 'failed')
RETURNING
    id, relative_path, file_size_bytes, file_mtime_ns, archive_sha256, import_status, import_attempts, import_error, discovered_at, import_started_at, imported_at
`

func (q *Queries) MarkArchiveImporting(ctx context.Context, id int64) (Archive, error) {
	row := q.db.QueryRowContext(ctx, markArchiveImporting, id)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.RelativePath,
		&i.FileSizeBytes,
		&i.FileMtimeNs,
		&i.ArchiveSha256,
		&i.ImportStatus,
		&i.ImportAttempts,
		&i.ImportError,
		&i.DiscoveredAt,
		&i.ImportStartedAt,
		&i.ImportedAt,
	)
	return i, err
}

const resetFailedArchive = `-- name: ResetFailedArchive :exec
UPDATE
    archives
SET
    import_status = 'discovered',
    import_error = NULL,
    import_started_at = NULL
WHERE
    id = ?1
    AND import_status = 'failed'
`

func (q *Queries) ResetFailedArchive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetFailedArchive, id)
	return err
}

const upsertDiscoveredArchive = `-- name: UpsertDiscoveredArchive :one
INSERT INTO
    archives (
        relative_path,
        file_size_bytes,
        file_mtime_ns,
        archive_sha256,
        import_status
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        'discovered'
    ) ON CONFLICT(relative_path) DO
UPDATE
SET
    file_size_bytes = excluded.file_size_bytes,
    file_mtime_ns = excluded.file_mtime_ns,
    archive_sha256 = COALESCE(
        excluded.archive_sha256,
        archives.archive_sha256
    )
WHERE
    archives.import_status != 'imported'
RETURNING
    id, relative_path, file_size_bytes, file_mtime_ns, archive_sha256, import_status, import_attempts, import_error, discovered_at, import_started_at, imported_at
`

type UpsertDiscoveredArchiveParams struct {
	RelativePath  string         `json:"relative_path"`
	FileSizeBytes int64          `json:"file_size_bytes"`
	FileMtimeNs   sql.NullInt64  `json:"file_mtime_ns"`
	ArchiveSha256 sql.NullString `json:"archive_sha256"`
}

// Use this when rescanning files that may already be known.
// It deliberately does not reset successfully imported archives.
func (q *Queries) UpsertDiscoveredArchive(ctx context.Context, arg UpsertDiscoveredArchiveParams) (Archive, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscoveredArchive,
		arg.RelativePath,
		arg.FileSizeBytes,
		arg.FileMtimeNs,
		arg.ArchiveSha256,
	)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.RelativePath,
		&i.FileSizeBytes,
		&i.FileMtimeNs,
		&i.ArchiveSha256,
		&i.ImportStatus,
		&i.ImportAttempts,
		&i.ImportError,
		&i.DiscoveredAt,
		&i.ImportStartedAt,
		&i.ImportedAt,
	)
	return i, err
}
