// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getDeviceByKey = `-- name: GetDeviceByKey :one
SELECT
    id, device_key, display_name, last_os, last_os_version, last_kernel, last_arch, last_cpu, last_memory_bytes, metadata_json, first_seen_at, last_seen_at, created_at
FROM
    devices
WHERE
    device_key = ?1
LIMIT
    1
`

func (q *Queries) GetDeviceByKey(ctx context.Context, deviceKey string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByKey, deviceKey)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceKey,
		&i.DisplayName,
		&i.LastOs,
		&i.LastOsVersion,
		&i.LastKernel,
		&i.LastArch,
		&i.LastCpu,
		&i.LastMemoryBytes,
		&i.MetadataJson,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT
    id, device_key, display_name, last_os, last_os_version, last_kernel, last_arch, last_cpu, last_memory_bytes, metadata_json, first_seen_at, last_seen_at, created_at
FROM
    devices
ORDER BY
    COALESCE(display_name, device_key)
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DeviceKey,
			&i.DisplayName,
			&i.LastOs,
			&i.LastOsVersion,
			&i.LastKernel,
			&i.LastArch,
			&i.LastCpu,
			&i.LastMemoryBytes,
			&i.MetadataJson,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleDevices = `-- name: ListStaleDevices :many
SELECT
    id, device_key, display_name, last_os, last_os_version, last_kernel, last_arch, last_cpu, last_memory_bytes, metadata_json, first_seen_at, last_seen_at, created_at
FROM
    devices
WHERE
    last_seen_at IS NULL
    OR last_seen_at < ?1
ORDER BY
    last_seen_at ASC
`

func (q *Queries) ListStaleDevices(ctx context.Context, cutoff sql.NullString) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listStaleDevices, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DeviceKey,
			&i.DisplayName,
			&i.LastOs,
			&i.LastOsVersion,
			&i.LastKernel,
			&i.LastArch,
			&i.LastCpu,
			&i.LastMemoryBytes,
			&i.MetadataJson,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO
    devices (
        device_key,
        display_name,
        last_os,
        last_os_version,
        last_kernel,
        last_arch,
        last_cpu,
        last_memory_bytes,
        metadata_json,
        first_seen_at,
        last_seen_at
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        ?10
    ) ON CONFLICT(device_key) DO
UPDATE
SET
    display_name = COALESCE(
        excluded.display_name,
        devices.display_name
    ),
    last_os = COALESCE(
        excluded.last_os,
        devices.last_os
    ),
    last_os_version = COALESCE(
        excluded.last_os_version,
        devices.last_os_version
    ),
    last_kernel = COALESCE(
        excluded.last_kernel,
        devices.last_kernel
    ),
    last_arch = COALESCE(
        excluded.last_arch,
        devices.last_arch
    ),
    last_cpu = COALESCE(
        excluded.last_cpu,
        devices.last_cpu
    ),
    last_memory_bytes = COALESCE(
        excluded.last_memory_bytes,
        devices.last_memory_bytes
    ),
    metadata_json = excluded.metadata_json,
    first_seen_at = COALESCE(
        devices.first_seen_at,
        excluded.first_seen_at
    ),
    last_seen_at = CASE
        WHEN devices.last_seen_at IS NULL
        OR excluded.last_seen_at > devices.last_seen_at THEN excluded.last_seen_at
        ELSE devices.last_seen_at
    END
RETURNING
    id, device_key, display_name, last_os, last_os_version, last_kernel, last_arch, last_cpu, last_memory_bytes, metadata_json, first_seen_at, last_seen_at, created_at
`

type UpsertDeviceParams struct {
	DeviceKey       string         `json:"device_key"`
	DisplayName     sql.NullString `json:"display_name"`
	LastOs          sql.NullString `json:"last_os"`
	LastOsVersion   sql.NullString `json:"last_os_version"`
	LastKernel      sql.NullString `json:"last_kernel"`
	LastArch        sql.NullString `json:"last_arch"`
	LastCpu         sql.NullString `json:"last_cpu"`
	LastMemoryBytes sql.NullInt64  `json:"last_memory_bytes"`
	MetadataJson    string         `json:"metadata_json"`
	SeenAt          sql.NullString `json:"seen_at"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, upsertDevice,
		arg.DeviceKey,
		arg.DisplayName,
		arg.LastOs,
		arg.LastOsVersion,
		arg.LastKernel,
		arg.LastArch,
		arg.LastCpu,
		arg.LastMemoryBytes,
		arg.MetadataJson,
		arg.SeenAt,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceKey,
		&i.DisplayName,
		&i.LastOs,
		&i.LastOsVersion,
		&i.LastKernel,
		&i.LastArch,
		&i.LastCpu,
		&i.LastMemoryBytes,
		&i.MetadataJson,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
