// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: features.sql

package sqlc

import (
	"context"
	"database/sql"
)

const linkTestFeature = `-- name: LinkTestFeature :exec
INSERT INTO
    test_features (test_case_id, feature_id)
VALUES
    (
        ?1,
        ?2
    ) ON CONFLICT(test_case_id, feature_id) DO NOTHING
`

type LinkTestFeatureParams struct {
	TestCaseID int64 `json:"test_case_id"`
	FeatureID  int64 `json:"feature_id"`
}

func (q *Queries) LinkTestFeature(ctx context.Context, arg LinkTestFeatureParams) error {
	_, err := q.db.ExecContext(ctx, linkTestFeature, arg.TestCaseID, arg.FeatureID)
	return err
}

const listFeaturesForTest = `-- name: ListFeaturesForTest :many
SELECT
    f.id, f.project_id, f.feature_key, f.name, f.description, f.source_file, f.source_symbol
FROM
    test_features tf
    JOIN features f ON f.id = tf.feature_id
WHERE
    tf.test_case_id = ?1
ORDER BY
    f.feature_key
`

func (q *Queries) ListFeaturesForTest(ctx context.Context, testCaseID int64) ([]Feature, error) {
	rows, err := q.db.QueryContext(ctx, listFeaturesForTest, testCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feature{}
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FeatureKey,
			&i.Name,
			&i.Description,
			&i.SourceFile,
			&i.SourceSymbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestsForFeature = `-- name: ListTestsForFeature :many
SELECT
    tc.id, tc.project_id, tc.test_key, tc.name, tc.suite, tc.result_kind, tc.source_file, tc.source_symbol, tc.first_seen_at, tc.last_seen_at, tc.metadata_json
FROM
    test_features tf
    JOIN test_cases tc ON tc.id = tf.test_case_id
WHERE
    tf.feature_id = ?1
ORDER BY
    tc.test_key
`

func (q *Queries) ListTestsForFeature(ctx context.Context, featureID int64) ([]TestCase, error) {
	rows, err := q.db.QueryContext(ctx, listTestsForFeature, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TestKey,
			&i.Name,
			&i.Suite,
			&i.ResultKind,
			&i.SourceFile,
			&i.SourceSymbol,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeature = `-- name: UpsertFeature :one
INSERT INTO
    features (
        project_id,
        feature_key,
        name,
        description,
        source_file,
        source_symbol
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6
    ) ON CONFLICT(project_id, feature_key) DO
UPDATE
SET
    name = COALESCE(excluded.name, features.name),
    description = COALESCE(
        excluded.description,
        features.description
    ),
    source_file = COALESCE(
        excluded.source_file,
        features.source_file
    ),
    source_symbol = COALESCE(
        excluded.source_symbol,
        features.source_symbol
    )
RETURNING
    id, project_id, feature_key, name, description, source_file, source_symbol
`

type UpsertFeatureParams struct {
	ProjectID    int64          `json:"project_id"`
	FeatureKey   string         `json:"feature_key"`
	Name         sql.NullString `json:"name"`
	Description  sql.NullString `json:"description"`
	SourceFile   sql.NullString `json:"source_file"`
	SourceSymbol sql.NullString `json:"source_symbol"`
}

func (q *Queries) UpsertFeature(ctx context.Context, arg UpsertFeatureParams) (Feature, error) {
	row := q.db.QueryRowContext(ctx, upsertFeature,
		arg.ProjectID,
		arg.FeatureKey,
		arg.Name,
		arg.Description,
		arg.SourceFile,
		arg.SourceSymbol,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FeatureKey,
		&i.Name,
		&i.Description,
		&i.SourceFile,
		&i.SourceSymbol,
	)
	return i, err
}
