// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fts5.sql

package sqlc

import (
	"context"
	"database/sql"
)

const searchTestResultMessages = `-- name: SearchTestResultMessages :many
SELECT
    tr.id,
    tr.run_id,
    tr.test_case_id,
    tr.status,
    tr.message,
    tr.stack_trace
FROM
    test_result_search AS fts
    JOIN test_results AS tr ON tr.id = fts.rowid
WHERE
    fts.message MATCH ?1
LIMIT
    ?2
`

type SearchTestResultMessagesParams struct {
	Query     string `json:"query"`
	LimitRows int64  `json:"limit_rows"`
}

type SearchTestResultMessagesRow struct {
	ID         int64          `json:"id"`
	RunID      int64          `json:"run_id"`
	TestCaseID int64          `json:"test_case_id"`
	Status     string         `json:"status"`
	Message    sql.NullString `json:"message"`
	StackTrace sql.NullString `json:"stack_trace"`
}

func (q *Queries) SearchTestResultMessages(ctx context.Context, arg SearchTestResultMessagesParams) ([]SearchTestResultMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTestResultMessages, arg.Query, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTestResultMessagesRow{}
	for rows.Next() {
		var i SearchTestResultMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TestCaseID,
			&i.Status,
			&i.Message,
			&i.StackTrace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
