// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Archive struct {
	ID              int64          `json:"id"`
	RelativePath    string         `json:"relative_path"`
	FileSizeBytes   int64          `json:"file_size_bytes"`
	FileMtimeNs     sql.NullInt64  `json:"file_mtime_ns"`
	ArchiveSha256   sql.NullString `json:"archive_sha256"`
	ImportStatus    string         `json:"import_status"`
	ImportAttempts  int64          `json:"import_attempts"`
	ImportError     sql.NullString `json:"import_error"`
	DiscoveredAt    string         `json:"discovered_at"`
	ImportStartedAt sql.NullString `json:"import_started_at"`
	ImportedAt      sql.NullString `json:"imported_at"`
}

type ArchiveFile struct {
	ID          int64  `json:"id"`
	RunID       int64  `json:"run_id"`
	ArchivePath string `json:"archive_path"`
	FileType    string `json:"file_type"`
	MediaType   string `json:"media_type"`
	SizeBytes   int64  `json:"size_bytes"`
	Sha256      string `json:"sha256"`
	IsPublic    int64  `json:"is_public"`
}

type Device struct {
	ID              int64          `json:"id"`
	DeviceKey       string         `json:"device_key"`
	DisplayName     sql.NullString `json:"display_name"`
	LastOs          sql.NullString `json:"last_os"`
	LastOsVersion   sql.NullString `json:"last_os_version"`
	LastKernel      sql.NullString `json:"last_kernel"`
	LastArch        sql.NullString `json:"last_arch"`
	LastCpu         sql.NullString `json:"last_cpu"`
	LastMemoryBytes sql.NullInt64  `json:"last_memory_bytes"`
	MetadataJson    string         `json:"metadata_json"`
	FirstSeenAt     sql.NullString `json:"first_seen_at"`
	LastSeenAt      sql.NullString `json:"last_seen_at"`
	CreatedAt       string         `json:"created_at"`
}

type Feature struct {
	ID           int64          `json:"id"`
	ProjectID    int64          `json:"project_id"`
	FeatureKey   string         `json:"feature_key"`
	Name         sql.NullString `json:"name"`
	Description  sql.NullString `json:"description"`
	SourceFile   sql.NullString `json:"source_file"`
	SourceSymbol sql.NullString `json:"source_symbol"`
}

type LatestTestStatusByDevice struct {
	ProjectID  int64          `json:"project_id"`
	TestCaseID int64          `json:"test_case_id"`
	TestKey    string         `json:"test_key"`
	TestName   string         `json:"test_name"`
	DeviceID   int64          `json:"device_id"`
	DeviceKey  string         `json:"device_key"`
	DeviceName sql.NullString `json:"device_name"`
	RunUid     string         `json:"run_uid"`
	CommitSha  string         `json:"commit_sha"`
	Branch     sql.NullString `json:"branch"`
	StartedAt  string         `json:"started_at"`
	Status     string         `json:"status"`
	DurationMs sql.NullInt64  `json:"duration_ms"`
	Message    sql.NullString `json:"message"`
}

type Project struct {
	ID         int64          `json:"id"`
	ProjectKey string         `json:"project_key"`
	Name       sql.NullString `json:"name"`
	Repository sql.NullString `json:"repository"`
	CreatedAt  string         `json:"created_at"`
}

type ResultFile struct {
	ResultID      int64  `json:"result_id"`
	ArchiveFileID int64  `json:"archive_file_id"`
	Relationship  string `json:"relationship"`
}

type Run struct {
	ID              int64          `json:"id"`
	RunUid          string         `json:"run_uid"`
	SchemaVersion   int64          `json:"schema_version"`
	ArchiveID       int64          `json:"archive_id"`
	ProjectID       int64          `json:"project_id"`
	DeviceID        int64          `json:"device_id"`
	SourceType      sql.NullString `json:"source_type"`
	SourceProvider  sql.NullString `json:"source_provider"`
	Workflow        sql.NullString `json:"workflow"`
	Job             sql.NullString `json:"job"`
	TriggerName     sql.NullString `json:"trigger_name"`
	SourceAttempt   int64          `json:"source_attempt"`
	CommitSha       string         `json:"commit_sha"`
	Branch          sql.NullString `json:"branch"`
	Tag             sql.NullString `json:"tag"`
	GitDirty        sql.NullInt64  `json:"git_dirty"`
	CommitTimestamp sql.NullString `json:"commit_timestamp"`
	StartedAt       string         `json:"started_at"`
	FinishedAt      string         `json:"finished_at"`
	DurationMs      int64          `json:"duration_ms"`
	Status          string         `json:"status"`
	TotalCount      int64          `json:"total_count"`
	PassedCount     int64          `json:"passed_count"`
	FailedCount     int64          `json:"failed_count"`
	SkippedCount    int64          `json:"skipped_count"`
	ErroredCount    int64          `json:"errored_count"`
	CancelledCount  int64          `json:"cancelled_count"`
	SoftwareJson    string         `json:"software_json"`
	EnvironmentJson string         `json:"environment_json"`
	LabelsJson      string         `json:"labels_json"`
	ManifestJson    string         `json:"manifest_json"`
	ImportedAt      string         `json:"imported_at"`
}

type TestCase struct {
	ID           int64          `json:"id"`
	ProjectID    int64          `json:"project_id"`
	TestKey      string         `json:"test_key"`
	Name         string         `json:"name"`
	Suite        sql.NullString `json:"suite"`
	ResultKind   string         `json:"result_kind"`
	SourceFile   sql.NullString `json:"source_file"`
	SourceSymbol sql.NullString `json:"source_symbol"`
	FirstSeenAt  sql.NullString `json:"first_seen_at"`
	LastSeenAt   sql.NullString `json:"last_seen_at"`
	MetadataJson string         `json:"metadata_json"`
}

type TestFeature struct {
	TestCaseID int64 `json:"test_case_id"`
	FeatureID  int64 `json:"feature_id"`
}

type TestResult struct {
	ID             int64          `json:"id"`
	RunID          int64          `json:"run_id"`
	TestCaseID     int64          `json:"test_case_id"`
	Attempt        int64          `json:"attempt"`
	Status         string         `json:"status"`
	StartedAt      sql.NullString `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	DurationMs     sql.NullInt64  `json:"duration_ms"`
	Message        sql.NullString `json:"message"`
	FailureKind    sql.NullString `json:"failure_kind"`
	FailurePhase   sql.NullString `json:"failure_phase"`
	FailureCode    sql.NullString `json:"failure_code"`
	ExpectedValue  sql.NullString `json:"expected_value"`
	ActualValue    sql.NullString `json:"actual_value"`
	StackTrace     sql.NullString `json:"stack_trace"`
	ParametersJson string         `json:"parameters_json"`
	MetricsJson    string         `json:"metrics_json"`
	LabelsJson     string         `json:"labels_json"`
	DetailsJson    string         `json:"details_json"`
}
