// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getProjectByID = `-- name: GetProjectByID :one
SELECT
    id, project_key, name, repository, created_at
FROM
    projects
WHERE
    id = ?1
LIMIT
    1
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Repository,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT
    id, project_key, name, repository, created_at
FROM
    projects
WHERE
    project_key = ?1
LIMIT
    1
`

func (q *Queries) GetProjectByKey(ctx context.Context, projectKey string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByKey, projectKey)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Repository,
		&i.CreatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT
    id, project_key, name, repository, created_at
FROM
    projects
ORDER BY
    project_key
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Repository,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO
    projects (project_key, name, repository)
VALUES
    (
        ?1,
        ?2,
        ?3
    ) ON CONFLICT(project_key) DO
UPDATE
SET
    name = COALESCE(excluded.name, projects.name),
    repository = COALESCE(excluded.repository, projects.repository)
RETURNING
    id, project_key, name, repository, created_at
`

type UpsertProjectParams struct {
	ProjectKey string         `json:"project_key"`
	Name       sql.NullString `json:"name"`
	Repository sql.NullString `json:"repository"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, upsertProject, arg.ProjectKey, arg.Name, arg.Repository)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Repository,
		&i.CreatedAt,
	)
	return i, err
}
