// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountArchivesByImportStatus(ctx context.Context) ([]CountArchivesByImportStatusRow, error)
	CountResultsForRun(ctx context.Context, runID int64) (CountResultsForRunRow, error)
	CountRuns(ctx context.Context) (int64, error)
	CreateArchive(ctx context.Context, arg CreateArchiveParams) (Archive, error)
	CreateArchiveFile(ctx context.Context, arg CreateArchiveFileParams) (ArchiveFile, error)
	CreateImportingArchive(ctx context.Context, arg CreateImportingArchiveParams) (Archive, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	CreateTestResult(ctx context.Context, arg CreateTestResultParams) (TestResult, error)
	FilterRuns(ctx context.Context, arg FilterRunsParams) ([]FilterRunsRow, error)
	FilterTestResults(ctx context.Context, arg FilterTestResultsParams) ([]FilterTestResultsRow, error)
	GetArchiveByID(ctx context.Context, id int64) (Archive, error)
	GetArchiveByPath(ctx context.Context, relativePath string) (Archive, error)
	GetArchiveFileByID(ctx context.Context, id int64) (GetArchiveFileByIDRow, error)
	GetCurrentFailuresOnBranch(ctx context.Context, arg GetCurrentFailuresOnBranchParams) ([]GetCurrentFailuresOnBranchRow, error)
	GetDeviceByKey(ctx context.Context, deviceKey string) (Device, error)
	GetLatestResultForTestAndDevice(ctx context.Context, arg GetLatestResultForTestAndDeviceParams) (GetLatestResultForTestAndDeviceRow, error)
	GetLatestRunForDevice(ctx context.Context, arg GetLatestRunForDeviceParams) (Run, error)
	GetLatestRunForProject(ctx context.Context, projectID int64) (Run, error)
	GetLatestRunForProjectBranch(ctx context.Context, arg GetLatestRunForProjectBranchParams) (Run, error)
	GetLatestTestStatusByDevice(ctx context.Context, arg GetLatestTestStatusByDeviceParams) ([]GetLatestTestStatusByDeviceRow, error)
	GetProjectByID(ctx context.Context, id int64) (Project, error)
	GetProjectByKey(ctx context.Context, projectKey string) (Project, error)
	// Use this for the public artifact endpoint.
	// It guarantees the returned entry is marked public.
	GetPublicArchiveFileByID(ctx context.Context, id int64) (GetPublicArchiveFileByIDRow, error)
	GetRunByArchiveID(ctx context.Context, archiveID int64) (Run, error)
	// Normally a duplicate run should make the import idempotently stop.
	GetRunByUID(ctx context.Context, runUid string) (Run, error)
	GetTestResultByID(ctx context.Context, id int64) (GetTestResultByIDRow, error)
	GetViewerSummary(ctx context.Context) (GetViewerSummaryRow, error)
	LinkResultFile(ctx context.Context, arg LinkResultFileParams) error
	LinkTestFeature(ctx context.Context, arg LinkTestFeatureParams) error
	ListArchiveFilesForRun(ctx context.Context, runID int64) ([]ArchiveFile, error)
	ListArchivesPendingImport(ctx context.Context, resultLimit int64) ([]Archive, error)
	ListCurrentFailures(ctx context.Context, arg ListCurrentFailuresParams) ([]ListCurrentFailuresRow, error)
	ListDevices(ctx context.Context) ([]Device, error)
	ListFailedArchives(ctx context.Context, resultLimit int64) ([]Archive, error)
	ListFailuresForRun(ctx context.Context, runID int64) ([]ListFailuresForRunRow, error)
	ListFeaturesForTest(ctx context.Context, testCaseID int64) ([]Feature, error)
	ListFilesForResult(ctx context.Context, resultID int64) ([]ListFilesForResultRow, error)
	ListLatestRunsByDevice(ctx context.Context, arg ListLatestRunsByDeviceParams) ([]ListLatestRunsByDeviceRow, error)
	ListMostFrequentFailures(ctx context.Context, arg ListMostFrequentFailuresParams) ([]ListMostFrequentFailuresRow, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListPublicArchiveFilesForRun(ctx context.Context, runID int64) ([]ArchiveFile, error)
	ListPublicFilesForResult(ctx context.Context, resultID int64) ([]ListPublicFilesForResultRow, error)
	ListResultsForRun(ctx context.Context, runID int64) ([]ListResultsForRunRow, error)
	ListRunSummaryHistory(ctx context.Context, arg ListRunSummaryHistoryParams) ([]ListRunSummaryHistoryRow, error)
	ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error)
	ListRunsByCommit(ctx context.Context, arg ListRunsByCommitParams) ([]ListRunsByCommitRow, error)
	ListRunsForDevice(ctx context.Context, arg ListRunsForDeviceParams) ([]Run, error)
	ListRunsForProject(ctx context.Context, arg ListRunsForProjectParams) ([]ListRunsForProjectRow, error)
	ListSlowestResultsForRun(ctx context.Context, arg ListSlowestResultsForRunParams) ([]ListSlowestResultsForRunRow, error)
	ListStaleDevices(ctx context.Context, cutoff sql.NullString) ([]Device, error)
	ListTestHistory(ctx context.Context, arg ListTestHistoryParams) ([]ListTestHistoryRow, error)
	ListTestHistoryForDevice(ctx context.Context, arg ListTestHistoryForDeviceParams) ([]ListTestHistoryForDeviceRow, error)
	ListTestsForFeature(ctx context.Context, featureID int64) ([]TestCase, error)
	ListViewerRuns(ctx context.Context) ([]ListViewerRunsRow, error)
	ListViewerTests(ctx context.Context) ([]ListViewerTestsRow, error)
	MarkArchiveFailed(ctx context.Context, arg MarkArchiveFailedParams) error
	MarkArchiveIgnored(ctx context.Context, arg MarkArchiveIgnoredParams) error
	MarkArchiveImported(ctx context.Context, id int64) error
	MarkArchiveImporting(ctx context.Context, id int64) (Archive, error)
	ResetFailedArchive(ctx context.Context, id int64) error
	RunUIDExists(ctx context.Context, runUid string) (bool, error)
	UpsertArchiveFile(ctx context.Context, arg UpsertArchiveFileParams) (ArchiveFile, error)
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error)
	// Use this when rescanning files that may already be known.
	// It deliberately does not reset successfully imported archives.
	UpsertDiscoveredArchive(ctx context.Context, arg UpsertDiscoveredArchiveParams) (Archive, error)
	UpsertFeature(ctx context.Context, arg UpsertFeatureParams) (Feature, error)
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error)
	UpsertTestCase(ctx context.Context, arg UpsertTestCaseParams) (TestCase, error)
	// Useful if an importer retry can encounter already inserted rows
	// within an otherwise incomplete run.
	UpsertTestResult(ctx context.Context, arg UpsertTestResultParams) (TestResult, error)
}

var _ Querier = (*Queries)(nil)
