// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countRuns = `-- name: CountRuns :one
SELECT
    COUNT(*)
FROM
    runs
`

func (q *Queries) CountRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO
    runs (
        run_uid,
        schema_version,
        archive_id,
        project_id,
        device_id,
        source_type,
        source_provider,
        workflow,
        job,
        trigger_name,
        source_attempt,
        commit_sha,
        branch,
        tag,
        git_dirty,
        commit_timestamp,
        started_at,
        finished_at,
        duration_ms,
        STATUS,
        total_count,
        passed_count,
        failed_count,
        skipped_count,
        errored_count,
        cancelled_count,
        software_json,
        environment_json,
        labels_json,
        manifest_json
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        ?11,
        ?12,
        ?13,
        ?14,
        ?15,
        ?16,
        ?17,
        ?18,
        ?19,
        ?20,
        ?21,
        ?22,
        ?23,
        ?24,
        ?25,
        ?26,
        ?27,
        ?28,
        ?29,
        ?30
    )
RETURNING
    id, run_uid, schema_version, archive_id, project_id, device_id, source_type, source_provider, workflow, job, trigger_name, source_attempt, commit_sha, branch, tag, git_dirty, commit_timestamp, started_at, finished_at, duration_ms, status, total_count, passed_count, failed_count, skipped_count, errored_count, cancelled_count, software_json, environment_json, labels_json, manifest_json, imported_at
`

type CreateRunParams struct {
	RunUid          string         `json:"run_uid"`
	SchemaVersion   int64          `json:"schema_version"`
	ArchiveID       int64          `json:"archive_id"`
	ProjectID       int64          `json:"project_id"`
	DeviceID        int64          `json:"device_id"`
	SourceType      sql.NullString `json:"source_type"`
	SourceProvider  sql.NullString `json:"source_provider"`
	Workflow        sql.NullString `json:"workflow"`
	Job             sql.NullString `json:"job"`
	TriggerName     sql.NullString `json:"trigger_name"`
	SourceAttempt   int64          `json:"source_attempt"`
	CommitSha       string         `json:"commit_sha"`
	Branch          sql.NullString `json:"branch"`
	Tag             sql.NullString `json:"tag"`
	GitDirty        sql.NullInt64  `json:"git_dirty"`
	CommitTimestamp sql.NullString `json:"commit_timestamp"`
	StartedAt       string         `json:"started_at"`
	FinishedAt      string         `json:"finished_at"`
	DurationMs      int64          `json:"duration_ms"`
	Status          string         `json:"status"`
	TotalCount      int64          `json:"total_count"`
	PassedCount     int64          `json:"passed_count"`
	FailedCount     int64          `json:"failed_count"`
	SkippedCount    int64          `json:"skipped_count"`
	ErroredCount    int64          `json:"errored_count"`
	CancelledCount  int64          `json:"cancelled_count"`
	SoftwareJson    string         `json:"software_json"`
	EnvironmentJson string         `json:"environment_json"`
	LabelsJson      string         `json:"labels_json"`
	ManifestJson    string         `json:"manifest_json"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.RunUid,
		arg.SchemaVersion,
		arg.ArchiveID,
		arg.ProjectID,
		arg.DeviceID,
		arg.SourceType,
		arg.SourceProvider,
		arg.Workflow,
		arg.Job,
		arg.TriggerName,
		arg.SourceAttempt,
		arg.CommitSha,
		arg.Branch,
		arg.Tag,
		arg.GitDirty,
		arg.CommitTimestamp,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.Status,
		arg.TotalCount,
		arg.PassedCount,
		arg.FailedCount,
		arg.SkippedCount,
		arg.ErroredCount,
		arg.CancelledCount,
		arg.SoftwareJson,
		arg.EnvironmentJson,
		arg.LabelsJson,
		arg.ManifestJson,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunUid,
		&i.SchemaVersion,
		&i.ArchiveID,
		&i.ProjectID,
		&i.DeviceID,
		&i.SourceType,
		&i.SourceProvider,
		&i.Workflow,
		&i.Job,
		&i.TriggerName,
		&i.SourceAttempt,
		&i.CommitSha,
		&i.Branch,
		&i.Tag,
		&i.GitDirty,
		&i.CommitTimestamp,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Status,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErroredCount,
		&i.CancelledCount,
		&i.SoftwareJson,
		&i.EnvironmentJson,
		&i.LabelsJson,
		&i.ManifestJson,
		&i.ImportedAt,
	)
	return i, err
}

const getLatestRunForDevice = `-- name: GetLatestRunForDevice :one
SELECT
    id, run_uid, schema_version, archive_id, project_id, device_id, source_type, source_provider, workflow, job, trigger_name, source_attempt, commit_sha, branch, tag, git_dirty, commit_timestamp, started_at, finished_at, duration_ms, status, total_count, passed_count, failed_count, skipped_count, errored_count, cancelled_count, software_json, environment_json, labels_json, manifest_json, imported_at
FROM
    runs
WHERE
    project_id = ?1
    AND device_id = ?2
ORDER BY
    started_at DESC,
    id DESC
LIMIT
    1
`

type GetLatestRunForDeviceParams struct {
	ProjectID int64 `json:"project_id"`
	DeviceID  int64 `json:"device_id"`
}

func (q *Queries) GetLatestRunForDevice(ctx context.Context, arg GetLatestRunForDeviceParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getLatestRunForDevice, arg.ProjectID, arg.DeviceID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunUid,
		&i.SchemaVersion,
		&i.ArchiveID,
		&i.ProjectID,
		&i.DeviceID,
		&i.SourceType,
		&i.SourceProvider,
		&i.Workflow,
		&i.Job,
		&i.TriggerName,
		&i.SourceAttempt,
		&i.CommitSha,
		&i.Branch,
		&i.Tag,
		&i.GitDirty,
		&i.CommitTimestamp,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Status,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErroredCount,
		&i.CancelledCount,
		&i.SoftwareJson,
		&i.EnvironmentJson,
		&i.LabelsJson,
		&i.ManifestJson,
		&i.ImportedAt,
	)
	return i, err
}

const getLatestRunForProject = `-- name: GetLatestRunForProject :one
SELECT
    id, run_uid, schema_version, archive_id, project_id, device_id, source_type, source_provider, workflow, job, trigger_name, source_attempt, commit_sha, branch, tag, git_dirty, commit_timestamp, started_at, finished_at, duration_ms, status, total_count, passed_count, failed_count, skipped_count, errored_count, cancelled_count, software_json, environment_json, labels_json, manifest_json, imported_at
FROM
    runs
WHERE
    project_id = ?1
ORDER BY
    started_at DESC,
    id DESC
LIMIT
    1
`

func (q *Queries) GetLatestRunForProject(ctx context.Context, projectID int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, getLatestRunForProject, projectID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunUid,
		&i.SchemaVersion,
		&i.ArchiveID,
		&i.ProjectID,
		&i.DeviceID,
		&i.SourceType,
		&i.SourceProvider,
		&i.Workflow,
		&i.Job,
		&i.TriggerName,
		&i.SourceAttempt,
		&i.CommitSha,
		&i.Branch,
		&i.Tag,
		&i.GitDirty,
		&i.CommitTimestamp,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Status,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErroredCount,
		&i.CancelledCount,
		&i.SoftwareJson,
		&i.EnvironmentJson,
		&i.LabelsJson,
		&i.ManifestJson,
		&i.ImportedAt,
	)
	return i, err
}

const getLatestRunForProjectBranch = `-- name: GetLatestRunForProjectBranch :one
SELECT
    id, run_uid, schema_version, archive_id, project_id, device_id, source_type, source_provider, workflow, job, trigger_name, source_attempt, commit_sha, branch, tag, git_dirty, commit_timestamp, started_at, finished_at, duration_ms, status, total_count, passed_count, failed_count, skipped_count, errored_count, cancelled_count, software_json, environment_json, labels_json, manifest_json, imported_at
FROM
    runs
WHERE
    project_id = ?1
    AND branch = ?2
ORDER BY
    started_at DESC,
    id DESC
LIMIT
    1
`

type GetLatestRunForProjectBranchParams struct {
	ProjectID int64          `json:"project_id"`
	Branch    sql.NullString `json:"branch"`
}

func (q *Queries) GetLatestRunForProjectBranch(ctx context.Context, arg GetLatestRunForProjectBranchParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, getLatestRunForProjectBranch, arg.ProjectID, arg.Branch)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunUid,
		&i.SchemaVersion,
		&i.ArchiveID,
		&i.ProjectID,
		&i.DeviceID,
		&i.SourceType,
		&i.SourceProvider,
		&i.Workflow,
		&i.Job,
		&i.TriggerName,
		&i.SourceAttempt,
		&i.CommitSha,
		&i.Branch,
		&i.Tag,
		&i.GitDirty,
		&i.CommitTimestamp,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Status,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErroredCount,
		&i.CancelledCount,
		&i.SoftwareJson,
		&i.EnvironmentJson,
		&i.LabelsJson,
		&i.ManifestJson,
		&i.ImportedAt,
	)
	return i, err
}

const getRunByArchiveID = `-- name: GetRunByArchiveID :one
SELECT
    id, run_uid, schema_version, archive_id, project_id, device_id, source_type, source_provider, workflow, job, trigger_name, source_attempt, commit_sha, branch, tag, git_dirty, commit_timestamp, started_at, finished_at, duration_ms, status, total_count, passed_count, failed_count, skipped_count, errored_count, cancelled_count, software_json, environment_json, labels_json, manifest_json, imported_at
FROM
    runs
WHERE
    archive_id = ?1
LIMIT
    1
`

func (q *Queries) GetRunByArchiveID(ctx context.Context, archiveID int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunByArchiveID, archiveID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunUid,
		&i.SchemaVersion,
		&i.ArchiveID,
		&i.ProjectID,
		&i.DeviceID,
		&i.SourceType,
		&i.SourceProvider,
		&i.Workflow,
		&i.Job,
		&i.TriggerName,
		&i.SourceAttempt,
		&i.CommitSha,
		&i.Branch,
		&i.Tag,
		&i.GitDirty,
		&i.CommitTimestamp,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Status,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErroredCount,
		&i.CancelledCount,
		&i.SoftwareJson,
		&i.EnvironmentJson,
		&i.LabelsJson,
		&i.ManifestJson,
		&i.ImportedAt,
	)
	return i, err
}

const getRunByUID = `-- name: GetRunByUID :one
SELECT
    id, run_uid, schema_version, archive_id, project_id, device_id, source_type, source_provider, workflow, job, trigger_name, source_attempt, commit_sha, branch, tag, git_dirty, commit_timestamp, started_at, finished_at, duration_ms, status, total_count, passed_count, failed_count, skipped_count, errored_count, cancelled_count, software_json, environment_json, labels_json, manifest_json, imported_at
FROM
    runs
WHERE
    run_uid = ?1
LIMIT
    1
`

// Normally a duplicate run should make the import idempotently stop.
func (q *Queries) GetRunByUID(ctx context.Context, runUid string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRunByUID, runUid)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunUid,
		&i.SchemaVersion,
		&i.ArchiveID,
		&i.ProjectID,
		&i.DeviceID,
		&i.SourceType,
		&i.SourceProvider,
		&i.Workflow,
		&i.Job,
		&i.TriggerName,
		&i.SourceAttempt,
		&i.CommitSha,
		&i.Branch,
		&i.Tag,
		&i.GitDirty,
		&i.CommitTimestamp,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Status,
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErroredCount,
		&i.CancelledCount,
		&i.SoftwareJson,
		&i.EnvironmentJson,
		&i.LabelsJson,
		&i.ManifestJson,
		&i.ImportedAt,
	)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT
    r.id, r.run_uid, r.schema_version, r.archive_id, r.project_id, r.device_id, r.source_type, r.source_provider, r.workflow, r.job, r.trigger_name, r.source_attempt, r.commit_sha, r.branch, r.tag, r.git_dirty, r.commit_timestamp, r.started_at, r.finished_at, r.duration_ms, r.status, r.total_count, r.passed_count, r.failed_count, r.skipped_count, r.errored_count, r.cancelled_count, r.software_json, r.environment_json, r.labels_json, r.manifest_json, r.imported_at,
    p.project_key,
    p.name AS project_name,
    d.device_key,
    d.display_name AS device_name
FROM
    runs r
    JOIN projects p ON p.id = r.project_id
    JOIN devices d ON d.id = r.device_id
ORDER BY
    r.started_at DESC,
    r.id DESC
LIMIT
    ?2 OFFSET ?1
`

type ListRunsParams struct {
	ResultOffset int64 `json:"result_offset"`
	ResultLimit  int64 `json:"result_limit"`
}

type ListRunsRow struct {
	ID              int64          `json:"id"`
	RunUid          string         `json:"run_uid"`
	SchemaVersion   int64          `json:"schema_version"`
	ArchiveID       int64          `json:"archive_id"`
	ProjectID       int64          `json:"project_id"`
	DeviceID        int64          `json:"device_id"`
	SourceType      sql.NullString `json:"source_type"`
	SourceProvider  sql.NullString `json:"source_provider"`
	Workflow        sql.NullString `json:"workflow"`
	Job             sql.NullString `json:"job"`
	TriggerName     sql.NullString `json:"trigger_name"`
	SourceAttempt   int64          `json:"source_attempt"`
	CommitSha       string         `json:"commit_sha"`
	Branch          sql.NullString `json:"branch"`
	Tag             sql.NullString `json:"tag"`
	GitDirty        sql.NullInt64  `json:"git_dirty"`
	CommitTimestamp sql.NullString `json:"commit_timestamp"`
	StartedAt       string         `json:"started_at"`
	FinishedAt      string         `json:"finished_at"`
	DurationMs      int64          `json:"duration_ms"`
	Status          string         `json:"status"`
	TotalCount      int64          `json:"total_count"`
	PassedCount     int64          `json:"passed_count"`
	FailedCount     int64          `json:"failed_count"`
	SkippedCount    int64          `json:"skipped_count"`
	ErroredCount    int64          `json:"errored_count"`
	CancelledCount  int64          `json:"cancelled_count"`
	SoftwareJson    string         `json:"software_json"`
	EnvironmentJson string         `json:"environment_json"`
	LabelsJson      string         `json:"labels_json"`
	ManifestJson    string         `json:"manifest_json"`
	ImportedAt      string         `json:"imported_at"`
	ProjectKey      string         `json:"project_key"`
	ProjectName     sql.NullString `json:"project_name"`
	DeviceKey       string         `json:"device_key"`
	DeviceName      sql.NullString `json:"device_name"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsRow{}
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunUid,
			&i.SchemaVersion,
			&i.ArchiveID,
			&i.ProjectID,
			&i.DeviceID,
			&i.SourceType,
			&i.SourceProvider,
			&i.Workflow,
			&i.Job,
			&i.TriggerName,
			&i.SourceAttempt,
			&i.CommitSha,
			&i.Branch,
			&i.Tag,
			&i.GitDirty,
			&i.CommitTimestamp,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Status,
			&i.TotalCount,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.ErroredCount,
			&i.CancelledCount,
			&i.SoftwareJson,
			&i.EnvironmentJson,
			&i.LabelsJson,
			&i.ManifestJson,
			&i.ImportedAt,
			&i.ProjectKey,
			&i.ProjectName,
			&i.DeviceKey,
			&i.DeviceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByCommit = `-- name: ListRunsByCommit :many
SELECT
    r.id, r.run_uid, r.schema_version, r.archive_id, r.project_id, r.device_id, r.source_type, r.source_provider, r.workflow, r.job, r.trigger_name, r.source_attempt, r.commit_sha, r.branch, r.tag, r.git_dirty, r.commit_timestamp, r.started_at, r.finished_at, r.duration_ms, r.status, r.total_count, r.passed_count, r.failed_count, r.skipped_count, r.errored_count, r.cancelled_count, r.software_json, r.environment_json, r.labels_json, r.manifest_json, r.imported_at,
    d.device_key,
    d.display_name AS device_name
FROM
    runs r
    JOIN devices d ON d.id = r.device_id
WHERE
    r.project_id = ?1
    AND r.commit_sha = ?2
ORDER BY
    r.started_at DESC,
    r.id DESC
`

type ListRunsByCommitParams struct {
	ProjectID int64  `json:"project_id"`
	CommitSha string `json:"commit_sha"`
}

type ListRunsByCommitRow struct {
	ID              int64          `json:"id"`
	RunUid          string         `json:"run_uid"`
	SchemaVersion   int64          `json:"schema_version"`
	ArchiveID       int64          `json:"archive_id"`
	ProjectID       int64          `json:"project_id"`
	DeviceID        int64          `json:"device_id"`
	SourceType      sql.NullString `json:"source_type"`
	SourceProvider  sql.NullString `json:"source_provider"`
	Workflow        sql.NullString `json:"workflow"`
	Job             sql.NullString `json:"job"`
	TriggerName     sql.NullString `json:"trigger_name"`
	SourceAttempt   int64          `json:"source_attempt"`
	CommitSha       string         `json:"commit_sha"`
	Branch          sql.NullString `json:"branch"`
	Tag             sql.NullString `json:"tag"`
	GitDirty        sql.NullInt64  `json:"git_dirty"`
	CommitTimestamp sql.NullString `json:"commit_timestamp"`
	StartedAt       string         `json:"started_at"`
	FinishedAt      string         `json:"finished_at"`
	DurationMs      int64          `json:"duration_ms"`
	Status          string         `json:"status"`
	TotalCount      int64          `json:"total_count"`
	PassedCount     int64          `json:"passed_count"`
	FailedCount     int64          `json:"failed_count"`
	SkippedCount    int64          `json:"skipped_count"`
	ErroredCount    int64          `json:"errored_count"`
	CancelledCount  int64          `json:"cancelled_count"`
	SoftwareJson    string         `json:"software_json"`
	EnvironmentJson string         `json:"environment_json"`
	LabelsJson      string         `json:"labels_json"`
	ManifestJson    string         `json:"manifest_json"`
	ImportedAt      string         `json:"imported_at"`
	DeviceKey       string         `json:"device_key"`
	DeviceName      sql.NullString `json:"device_name"`
}

func (q *Queries) ListRunsByCommit(ctx context.Context, arg ListRunsByCommitParams) ([]ListRunsByCommitRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunsByCommit, arg.ProjectID, arg.CommitSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsByCommitRow{}
	for rows.Next() {
		var i ListRunsByCommitRow
		if err := rows.Scan(
			&i.ID,
			&i.RunUid,
			&i.SchemaVersion,
			&i.ArchiveID,
			&i.ProjectID,
			&i.DeviceID,
			&i.SourceType,
			&i.SourceProvider,
			&i.Workflow,
			&i.Job,
			&i.TriggerName,
			&i.SourceAttempt,
			&i.CommitSha,
			&i.Branch,
			&i.Tag,
			&i.GitDirty,
			&i.CommitTimestamp,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Status,
			&i.TotalCount,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.ErroredCount,
			&i.CancelledCount,
			&i.SoftwareJson,
			&i.EnvironmentJson,
			&i.LabelsJson,
			&i.ManifestJson,
			&i.ImportedAt,
			&i.DeviceKey,
			&i.DeviceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForDevice = `-- name: ListRunsForDevice :many
SELECT
    id, run_uid, schema_version, archive_id, project_id, device_id, source_type, source_provider, workflow, job, trigger_name, source_attempt, commit_sha, branch, tag, git_dirty, commit_timestamp, started_at, finished_at, duration_ms, status, total_count, passed_count, failed_count, skipped_count, errored_count, cancelled_count, software_json, environment_json, labels_json, manifest_json, imported_at
FROM
    runs
WHERE
    project_id = ?1
    AND device_id = ?2
ORDER BY
    started_at DESC,
    id DESC
LIMIT
    ?4 OFFSET ?3
`

type ListRunsForDeviceParams struct {
	ProjectID    int64 `json:"project_id"`
	DeviceID     int64 `json:"device_id"`
	ResultOffset int64 `json:"result_offset"`
	ResultLimit  int64 `json:"result_limit"`
}

func (q *Queries) ListRunsForDevice(ctx context.Context, arg ListRunsForDeviceParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRunsForDevice,
		arg.ProjectID,
		arg.DeviceID,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.RunUid,
			&i.SchemaVersion,
			&i.ArchiveID,
			&i.ProjectID,
			&i.DeviceID,
			&i.SourceType,
			&i.SourceProvider,
			&i.Workflow,
			&i.Job,
			&i.TriggerName,
			&i.SourceAttempt,
			&i.CommitSha,
			&i.Branch,
			&i.Tag,
			&i.GitDirty,
			&i.CommitTimestamp,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Status,
			&i.TotalCount,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.ErroredCount,
			&i.CancelledCount,
			&i.SoftwareJson,
			&i.EnvironmentJson,
			&i.LabelsJson,
			&i.ManifestJson,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForProject = `-- name: ListRunsForProject :many
SELECT
    r.id, r.run_uid, r.schema_version, r.archive_id, r.project_id, r.device_id, r.source_type, r.source_provider, r.workflow, r.job, r.trigger_name, r.source_attempt, r.commit_sha, r.branch, r.tag, r.git_dirty, r.commit_timestamp, r.started_at, r.finished_at, r.duration_ms, r.status, r.total_count, r.passed_count, r.failed_count, r.skipped_count, r.errored_count, r.cancelled_count, r.software_json, r.environment_json, r.labels_json, r.manifest_json, r.imported_at,
    d.device_key,
    d.display_name AS device_name
FROM
    runs r
    JOIN devices d ON d.id = r.device_id
WHERE
    r.project_id = ?1
ORDER BY
    r.started_at DESC,
    r.id DESC
LIMIT
    ?3 OFFSET ?2
`

type ListRunsForProjectParams struct {
	ProjectID    int64 `json:"project_id"`
	ResultOffset int64 `json:"result_offset"`
	ResultLimit  int64 `json:"result_limit"`
}

type ListRunsForProjectRow struct {
	ID              int64          `json:"id"`
	RunUid          string         `json:"run_uid"`
	SchemaVersion   int64          `json:"schema_version"`
	ArchiveID       int64          `json:"archive_id"`
	ProjectID       int64          `json:"project_id"`
	DeviceID        int64          `json:"device_id"`
	SourceType      sql.NullString `json:"source_type"`
	SourceProvider  sql.NullString `json:"source_provider"`
	Workflow        sql.NullString `json:"workflow"`
	Job             sql.NullString `json:"job"`
	TriggerName     sql.NullString `json:"trigger_name"`
	SourceAttempt   int64          `json:"source_attempt"`
	CommitSha       string         `json:"commit_sha"`
	Branch          sql.NullString `json:"branch"`
	Tag             sql.NullString `json:"tag"`
	GitDirty        sql.NullInt64  `json:"git_dirty"`
	CommitTimestamp sql.NullString `json:"commit_timestamp"`
	StartedAt       string         `json:"started_at"`
	FinishedAt      string         `json:"finished_at"`
	DurationMs      int64          `json:"duration_ms"`
	Status          string         `json:"status"`
	TotalCount      int64          `json:"total_count"`
	PassedCount     int64          `json:"passed_count"`
	FailedCount     int64          `json:"failed_count"`
	SkippedCount    int64          `json:"skipped_count"`
	ErroredCount    int64          `json:"errored_count"`
	CancelledCount  int64          `json:"cancelled_count"`
	SoftwareJson    string         `json:"software_json"`
	EnvironmentJson string         `json:"environment_json"`
	LabelsJson      string         `json:"labels_json"`
	ManifestJson    string         `json:"manifest_json"`
	ImportedAt      string         `json:"imported_at"`
	DeviceKey       string         `json:"device_key"`
	DeviceName      sql.NullString `json:"device_name"`
}

func (q *Queries) ListRunsForProject(ctx context.Context, arg ListRunsForProjectParams) ([]ListRunsForProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunsForProject, arg.ProjectID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsForProjectRow{}
	for rows.Next() {
		var i ListRunsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.RunUid,
			&i.SchemaVersion,
			&i.ArchiveID,
			&i.ProjectID,
			&i.DeviceID,
			&i.SourceType,
			&i.SourceProvider,
			&i.Workflow,
			&i.Job,
			&i.TriggerName,
			&i.SourceAttempt,
			&i.CommitSha,
			&i.Branch,
			&i.Tag,
			&i.GitDirty,
			&i.CommitTimestamp,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Status,
			&i.TotalCount,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.ErroredCount,
			&i.CancelledCount,
			&i.SoftwareJson,
			&i.EnvironmentJson,
			&i.LabelsJson,
			&i.ManifestJson,
			&i.ImportedAt,
			&i.DeviceKey,
			&i.DeviceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runUIDExists = `-- name: RunUIDExists :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            runs
        WHERE
            run_uid = ?1
    ) AS exists_flag
`

func (q *Queries) RunUIDExists(ctx context.Context, runUid string) (bool, error) {
	row := q.db.QueryRowContext(ctx, runUIDExists, runUid)
	var exists_flag bool
	err := row.Scan(&exists_flag)
	return exists_flag, err
}
