// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: selects.sql

package sqlc

import (
	"context"
	"database/sql"
)

const filterRuns = `-- name: FilterRuns :many
SELECT
    r.id,
    r.run_uid,
    r.commit_sha,
    r.branch,
    r.tag,
    r.source_type,
    r.status,
    r.started_at,
    r.finished_at,
    r.duration_ms,
    r.total_count,
    r.passed_count,
    r.failed_count,
    r.skipped_count,
    r.errored_count,
    r.cancelled_count,
    p.project_key,
    p.name AS project_name,
    d.device_key,
    d.display_name AS device_name,
    d.last_os AS device_os,
    d.last_arch AS device_arch
FROM
    runs r
    JOIN projects p ON p.id = r.project_id
    JOIN devices d ON d.id = r.device_id
WHERE
    r.project_id = ?1
    AND (
        ?2 IS NULL
        OR r.branch = ?2
    )
    AND (
        ?3 IS NULL
        OR r.device_id = ?3
    )
    AND (
        ?4 IS NULL
        OR r.status = ?4
    )
    AND (
        ?5 IS NULL
        OR r.source_type = ?5
    )
    AND (
        ?6 IS NULL
        OR r.commit_sha LIKE ?6 || '%'
    )
    AND (
        ?7 IS NULL
        OR r.started_at >= ?7
    )
    AND (
        ?8 IS NULL
        OR r.started_at < ?8
    )
ORDER BY
    r.started_at DESC,
    r.id DESC
LIMIT
    ?10 OFFSET ?9
`

type FilterRunsParams struct {
	ProjectID    int64       `json:"project_id"`
	Branch       interface{} `json:"branch"`
	DeviceID     interface{} `json:"device_id"`
	Status       interface{} `json:"status"`
	SourceType   interface{} `json:"source_type"`
	CommitPrefix interface{} `json:"commit_prefix"`
	StartedFrom  interface{} `json:"started_from"`
	StartedUntil interface{} `json:"started_until"`
	ResultOffset int64       `json:"result_offset"`
	ResultLimit  int64       `json:"result_limit"`
}

type FilterRunsRow struct {
	ID             int64          `json:"id"`
	RunUid         string         `json:"run_uid"`
	CommitSha      string         `json:"commit_sha"`
	Branch         sql.NullString `json:"branch"`
	Tag            sql.NullString `json:"tag"`
	SourceType     sql.NullString `json:"source_type"`
	Status         string         `json:"status"`
	StartedAt      string         `json:"started_at"`
	FinishedAt     string         `json:"finished_at"`
	DurationMs     int64          `json:"duration_ms"`
	TotalCount     int64          `json:"total_count"`
	PassedCount    int64          `json:"passed_count"`
	FailedCount    int64          `json:"failed_count"`
	SkippedCount   int64          `json:"skipped_count"`
	ErroredCount   int64          `json:"errored_count"`
	CancelledCount int64          `json:"cancelled_count"`
	ProjectKey     string         `json:"project_key"`
	ProjectName    sql.NullString `json:"project_name"`
	DeviceKey      string         `json:"device_key"`
	DeviceName     sql.NullString `json:"device_name"`
	DeviceOs       sql.NullString `json:"device_os"`
	DeviceArch     sql.NullString `json:"device_arch"`
}

func (q *Queries) FilterRuns(ctx context.Context, arg FilterRunsParams) ([]FilterRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, filterRuns,
		arg.ProjectID,
		arg.Branch,
		arg.DeviceID,
		arg.Status,
		arg.SourceType,
		arg.CommitPrefix,
		arg.StartedFrom,
		arg.StartedUntil,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterRunsRow{}
	for rows.Next() {
		var i FilterRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunUid,
			&i.CommitSha,
			&i.Branch,
			&i.Tag,
			&i.SourceType,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.TotalCount,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.ErroredCount,
			&i.CancelledCount,
			&i.ProjectKey,
			&i.ProjectName,
			&i.DeviceKey,
			&i.DeviceName,
			&i.DeviceOs,
			&i.DeviceArch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentFailuresOnBranch = `-- name: GetCurrentFailuresOnBranch :many
SELECT
    r.run_uid,
    r.commit_sha,
    r.started_at,
    d.device_key,
    tc.test_key,
    tc.name,
    tr.status,
    tr.duration_ms,
    tr.failure_kind,
    tr.failure_code,
    tr.message
FROM
    test_results tr
    JOIN runs r ON r.id = tr.run_id
    JOIN devices d ON d.id = r.device_id
    JOIN test_cases tc ON tc.id = tr.test_case_id
WHERE
    r.project_id = ?
    AND r.branch = ?
    AND tr.status IN ('failed', 'error')
ORDER BY
    r.started_at DESC,
    tc.test_key
LIMIT
    ?
`

type GetCurrentFailuresOnBranchParams struct {
	ProjectID int64          `json:"project_id"`
	Branch    sql.NullString `json:"branch"`
	Limit     int64          `json:"limit"`
}

type GetCurrentFailuresOnBranchRow struct {
	RunUid      string         `json:"run_uid"`
	CommitSha   string         `json:"commit_sha"`
	StartedAt   string         `json:"started_at"`
	DeviceKey   string         `json:"device_key"`
	TestKey     string         `json:"test_key"`
	Name        string         `json:"name"`
	Status      string         `json:"status"`
	DurationMs  sql.NullInt64  `json:"duration_ms"`
	FailureKind sql.NullString `json:"failure_kind"`
	FailureCode sql.NullString `json:"failure_code"`
	Message     sql.NullString `json:"message"`
}

func (q *Queries) GetCurrentFailuresOnBranch(ctx context.Context, arg GetCurrentFailuresOnBranchParams) ([]GetCurrentFailuresOnBranchRow, error) {
	rows, err := q.db.QueryContext(ctx, getCurrentFailuresOnBranch, arg.ProjectID, arg.Branch, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCurrentFailuresOnBranchRow{}
	for rows.Next() {
		var i GetCurrentFailuresOnBranchRow
		if err := rows.Scan(
			&i.RunUid,
			&i.CommitSha,
			&i.StartedAt,
			&i.DeviceKey,
			&i.TestKey,
			&i.Name,
			&i.Status,
			&i.DurationMs,
			&i.FailureKind,
			&i.FailureCode,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestTestStatusByDevice = `-- name: GetLatestTestStatusByDevice :many
WITH ranked AS (
    SELECT
        r.id, r.run_uid, r.schema_version, r.archive_id, r.project_id, r.device_id, r.source_type, r.source_provider, r.workflow, r.job, r.trigger_name, r.source_attempt, r.commit_sha, r.branch, r.tag, r.git_dirty, r.commit_timestamp, r.started_at, r.finished_at, r.duration_ms, r.status, r.total_count, r.passed_count, r.failed_count, r.skipped_count, r.errored_count, r.cancelled_count, r.software_json, r.environment_json, r.labels_json, r.manifest_json, r.imported_at,
        d.device_key,
        d.display_name,
        row_number() OVER (
            PARTITION BY r.project_id,
            r.device_id
            ORDER BY
                r.started_at DESC,
                r.id DESC
        ) AS position
    FROM
        runs r
        JOIN devices d ON d.id = r.device_id
    WHERE
        r.project_id = ?
        AND (
            ? IS NULL
            OR r.branch = ?
        )
)
SELECT
    id, run_uid, schema_version, archive_id, project_id, device_id, source_type, source_provider, workflow, job, trigger_name, source_attempt, commit_sha, branch, tag, git_dirty, commit_timestamp, started_at, finished_at, duration_ms, status, total_count, passed_count, failed_count, skipped_count, errored_count, cancelled_count, software_json, environment_json, labels_json, manifest_json, imported_at, device_key, display_name, position
FROM
    ranked
WHERE
    position = 1
ORDER BY
    device_key
`

type GetLatestTestStatusByDeviceParams struct {
	ProjectID int64          `json:"project_id"`
	Column2   interface{}    `json:"column_2"`
	Branch    sql.NullString `json:"branch"`
}

type GetLatestTestStatusByDeviceRow struct {
	ID              int64          `json:"id"`
	RunUid          string         `json:"run_uid"`
	SchemaVersion   int64          `json:"schema_version"`
	ArchiveID       int64          `json:"archive_id"`
	ProjectID       int64          `json:"project_id"`
	DeviceID        int64          `json:"device_id"`
	SourceType      sql.NullString `json:"source_type"`
	SourceProvider  sql.NullString `json:"source_provider"`
	Workflow        sql.NullString `json:"workflow"`
	Job             sql.NullString `json:"job"`
	TriggerName     sql.NullString `json:"trigger_name"`
	SourceAttempt   int64          `json:"source_attempt"`
	CommitSha       string         `json:"commit_sha"`
	Branch          sql.NullString `json:"branch"`
	Tag             sql.NullString `json:"tag"`
	GitDirty        sql.NullInt64  `json:"git_dirty"`
	CommitTimestamp sql.NullString `json:"commit_timestamp"`
	StartedAt       string         `json:"started_at"`
	FinishedAt      string         `json:"finished_at"`
	DurationMs      int64          `json:"duration_ms"`
	Status          string         `json:"status"`
	TotalCount      int64          `json:"total_count"`
	PassedCount     int64          `json:"passed_count"`
	FailedCount     int64          `json:"failed_count"`
	SkippedCount    int64          `json:"skipped_count"`
	ErroredCount    int64          `json:"errored_count"`
	CancelledCount  int64          `json:"cancelled_count"`
	SoftwareJson    string         `json:"software_json"`
	EnvironmentJson string         `json:"environment_json"`
	LabelsJson      string         `json:"labels_json"`
	ManifestJson    string         `json:"manifest_json"`
	ImportedAt      string         `json:"imported_at"`
	DeviceKey       string         `json:"device_key"`
	DisplayName     sql.NullString `json:"display_name"`
	Position        interface{}    `json:"position"`
}

func (q *Queries) GetLatestTestStatusByDevice(ctx context.Context, arg GetLatestTestStatusByDeviceParams) ([]GetLatestTestStatusByDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestTestStatusByDevice, arg.ProjectID, arg.Column2, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLatestTestStatusByDeviceRow{}
	for rows.Next() {
		var i GetLatestTestStatusByDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.RunUid,
			&i.SchemaVersion,
			&i.ArchiveID,
			&i.ProjectID,
			&i.DeviceID,
			&i.SourceType,
			&i.SourceProvider,
			&i.Workflow,
			&i.Job,
			&i.TriggerName,
			&i.SourceAttempt,
			&i.CommitSha,
			&i.Branch,
			&i.Tag,
			&i.GitDirty,
			&i.CommitTimestamp,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Status,
			&i.TotalCount,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.ErroredCount,
			&i.CancelledCount,
			&i.SoftwareJson,
			&i.EnvironmentJson,
			&i.LabelsJson,
			&i.ManifestJson,
			&i.ImportedAt,
			&i.DeviceKey,
			&i.DisplayName,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentFailures = `-- name: ListCurrentFailures :many
WITH latest_runs AS (
    SELECT
        id
    FROM
        (
            SELECT
                r.id,
                ROW_NUMBER() OVER (
                    PARTITION BY r.device_id
                    ORDER BY
                        r.started_at DESC,
                        r.id DESC
                ) AS rank_number
            FROM
                runs r
            WHERE
                r.project_id = ?1
                AND (
                    ?2 IS NULL
                    OR r.branch = ?2
                )
        )
    WHERE
        rank_number = 1
)
SELECT
    tr.id AS result_id,
    tr.status,
    tr.duration_ms,
    tr.message,
    tr.failure_kind,
    tr.failure_code,
    tc.id AS test_case_id,
    tc.test_key,
    tc.name AS test_name,
    tc.suite,
    r.run_uid,
    r.commit_sha,
    r.branch,
    r.started_at,
    d.id AS device_id,
    d.device_key,
    d.display_name AS device_name
FROM
    test_results tr
    JOIN latest_runs lr ON lr.id = tr.run_id
    JOIN runs r ON r.id = tr.run_id
    JOIN test_cases tc ON tc.id = tr.test_case_id
    JOIN devices d ON d.id = r.device_id
WHERE
    tr.status IN ('failed', 'error')
ORDER BY
    CASE
        tr.status
        WHEN 'error' THEN 0
        ELSE 1
    END,
    tc.test_key,
    d.device_key
`

type ListCurrentFailuresParams struct {
	ProjectID int64       `json:"project_id"`
	Branch    interface{} `json:"branch"`
}

type ListCurrentFailuresRow struct {
	ResultID    int64          `json:"result_id"`
	Status      string         `json:"status"`
	DurationMs  sql.NullInt64  `json:"duration_ms"`
	Message     sql.NullString `json:"message"`
	FailureKind sql.NullString `json:"failure_kind"`
	FailureCode sql.NullString `json:"failure_code"`
	TestCaseID  int64          `json:"test_case_id"`
	TestKey     string         `json:"test_key"`
	TestName    string         `json:"test_name"`
	Suite       sql.NullString `json:"suite"`
	RunUid      string         `json:"run_uid"`
	CommitSha   string         `json:"commit_sha"`
	Branch      sql.NullString `json:"branch"`
	StartedAt   string         `json:"started_at"`
	DeviceID    int64          `json:"device_id"`
	DeviceKey   string         `json:"device_key"`
	DeviceName  sql.NullString `json:"device_name"`
}

func (q *Queries) ListCurrentFailures(ctx context.Context, arg ListCurrentFailuresParams) ([]ListCurrentFailuresRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentFailures, arg.ProjectID, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentFailuresRow{}
	for rows.Next() {
		var i ListCurrentFailuresRow
		if err := rows.Scan(
			&i.ResultID,
			&i.Status,
			&i.DurationMs,
			&i.Message,
			&i.FailureKind,
			&i.FailureCode,
			&i.TestCaseID,
			&i.TestKey,
			&i.TestName,
			&i.Suite,
			&i.RunUid,
			&i.CommitSha,
			&i.Branch,
			&i.StartedAt,
			&i.DeviceID,
			&i.DeviceKey,
			&i.DeviceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestRunsByDevice = `-- name: ListLatestRunsByDevice :many
WITH ranked_runs AS (
    SELECT
        r.id, r.run_uid, r.schema_version, r.archive_id, r.project_id, r.device_id, r.source_type, r.source_provider, r.workflow, r.job, r.trigger_name, r.source_attempt, r.commit_sha, r.branch, r.tag, r.git_dirty, r.commit_timestamp, r.started_at, r.finished_at, r.duration_ms, r.status, r.total_count, r.passed_count, r.failed_count, r.skipped_count, r.errored_count, r.cancelled_count, r.software_json, r.environment_json, r.labels_json, r.manifest_json, r.imported_at,
        ROW_NUMBER() OVER (
            PARTITION BY r.device_id
            ORDER BY
                r.started_at DESC,
                r.id DESC
        ) AS rank_number
    FROM
        runs r
    WHERE
        r.project_id = ?1
        AND (
            ?2 IS NULL
            OR r.branch = ?2
        )
)
SELECT
    rr.id,
    rr.run_uid,
    rr.commit_sha,
    rr.branch,
    rr.status,
    rr.started_at,
    rr.duration_ms,
    rr.total_count,
    rr.passed_count,
    rr.failed_count,
    rr.skipped_count,
    rr.errored_count,
    rr.cancelled_count,
    d.id AS device_id,
    d.device_key,
    d.display_name AS device_name,
    d.last_os,
    d.last_arch
FROM
    ranked_runs rr
    JOIN devices d ON d.id = rr.device_id
WHERE
    rr.rank_number = 1
ORDER BY
    COALESCE(d.display_name, d.device_key)
`

type ListLatestRunsByDeviceParams struct {
	ProjectID int64       `json:"project_id"`
	Branch    interface{} `json:"branch"`
}

type ListLatestRunsByDeviceRow struct {
	ID             int64          `json:"id"`
	RunUid         string         `json:"run_uid"`
	CommitSha      string         `json:"commit_sha"`
	Branch         sql.NullString `json:"branch"`
	Status         string         `json:"status"`
	StartedAt      string         `json:"started_at"`
	DurationMs     int64          `json:"duration_ms"`
	TotalCount     int64          `json:"total_count"`
	PassedCount    int64          `json:"passed_count"`
	FailedCount    int64          `json:"failed_count"`
	SkippedCount   int64          `json:"skipped_count"`
	ErroredCount   int64          `json:"errored_count"`
	CancelledCount int64          `json:"cancelled_count"`
	DeviceID       int64          `json:"device_id"`
	DeviceKey      string         `json:"device_key"`
	DeviceName     sql.NullString `json:"device_name"`
	LastOs         sql.NullString `json:"last_os"`
	LastArch       sql.NullString `json:"last_arch"`
}

func (q *Queries) ListLatestRunsByDevice(ctx context.Context, arg ListLatestRunsByDeviceParams) ([]ListLatestRunsByDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestRunsByDevice, arg.ProjectID, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestRunsByDeviceRow{}
	for rows.Next() {
		var i ListLatestRunsByDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.RunUid,
			&i.CommitSha,
			&i.Branch,
			&i.Status,
			&i.StartedAt,
			&i.DurationMs,
			&i.TotalCount,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.ErroredCount,
			&i.CancelledCount,
			&i.DeviceID,
			&i.DeviceKey,
			&i.DeviceName,
			&i.LastOs,
			&i.LastArch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMostFrequentFailures = `-- name: ListMostFrequentFailures :many
SELECT
    tc.id AS test_case_id,
    tc.test_key,
    tc.name AS test_name,
    tc.suite,
    COUNT(*) AS failure_count,
    MAX(r.started_at) AS last_failed_at
FROM
    test_results tr
    JOIN test_cases tc ON tc.id = tr.test_case_id
    JOIN runs r ON r.id = tr.run_id
WHERE
    r.project_id = ?1
    AND tr.status IN ('failed', 'error')
    AND (
        ?2 IS NULL
        OR r.branch = ?2
    )
    AND (
        ?3 IS NULL
        OR r.device_id = ?3
    )
    AND (
        ?4 IS NULL
        OR r.started_at >= ?4
    )
GROUP BY
    tc.id,
    tc.test_key,
    tc.name,
    tc.suite
ORDER BY
    failure_count DESC,
    last_failed_at DESC
LIMIT
    ?5
`

type ListMostFrequentFailuresParams struct {
	ProjectID   int64       `json:"project_id"`
	Branch      interface{} `json:"branch"`
	DeviceID    interface{} `json:"device_id"`
	StartedFrom interface{} `json:"started_from"`
	ResultLimit int64       `json:"result_limit"`
}

type ListMostFrequentFailuresRow struct {
	TestCaseID   int64          `json:"test_case_id"`
	TestKey      string         `json:"test_key"`
	TestName     string         `json:"test_name"`
	Suite        sql.NullString `json:"suite"`
	FailureCount int64          `json:"failure_count"`
	LastFailedAt interface{}    `json:"last_failed_at"`
}

func (q *Queries) ListMostFrequentFailures(ctx context.Context, arg ListMostFrequentFailuresParams) ([]ListMostFrequentFailuresRow, error) {
	rows, err := q.db.QueryContext(ctx, listMostFrequentFailures,
		arg.ProjectID,
		arg.Branch,
		arg.DeviceID,
		arg.StartedFrom,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMostFrequentFailuresRow{}
	for rows.Next() {
		var i ListMostFrequentFailuresRow
		if err := rows.Scan(
			&i.TestCaseID,
			&i.TestKey,
			&i.TestName,
			&i.Suite,
			&i.FailureCount,
			&i.LastFailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSummaryHistory = `-- name: ListRunSummaryHistory :many
SELECT
    r.run_uid,
    r.commit_sha,
    r.branch,
    r.started_at,
    r.duration_ms,
    r.status,
    r.passed_count,
    r.failed_count,
    r.skipped_count,
    r.errored_count,
    r.cancelled_count,
    d.device_key,
    d.display_name AS device_name
FROM
    runs r
    JOIN devices d ON d.id = r.device_id
WHERE
    r.project_id = ?1
    AND (
        ?2 IS NULL
        OR r.branch = ?2
    )
    AND (
        ?3 IS NULL
        OR r.device_id = ?3
    )
ORDER BY
    r.started_at DESC,
    r.id DESC
LIMIT
    ?4
`

type ListRunSummaryHistoryParams struct {
	ProjectID   int64       `json:"project_id"`
	Branch      interface{} `json:"branch"`
	DeviceID    interface{} `json:"device_id"`
	ResultLimit int64       `json:"result_limit"`
}

type ListRunSummaryHistoryRow struct {
	RunUid         string         `json:"run_uid"`
	CommitSha      string         `json:"commit_sha"`
	Branch         sql.NullString `json:"branch"`
	StartedAt      string         `json:"started_at"`
	DurationMs     int64          `json:"duration_ms"`
	Status         string         `json:"status"`
	PassedCount    int64          `json:"passed_count"`
	FailedCount    int64          `json:"failed_count"`
	SkippedCount   int64          `json:"skipped_count"`
	ErroredCount   int64          `json:"errored_count"`
	CancelledCount int64          `json:"cancelled_count"`
	DeviceKey      string         `json:"device_key"`
	DeviceName     sql.NullString `json:"device_name"`
}

func (q *Queries) ListRunSummaryHistory(ctx context.Context, arg ListRunSummaryHistoryParams) ([]ListRunSummaryHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunSummaryHistory,
		arg.ProjectID,
		arg.Branch,
		arg.DeviceID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunSummaryHistoryRow{}
	for rows.Next() {
		var i ListRunSummaryHistoryRow
		if err := rows.Scan(
			&i.RunUid,
			&i.CommitSha,
			&i.Branch,
			&i.StartedAt,
			&i.DurationMs,
			&i.Status,
			&i.PassedCount,
			&i.FailedCount,
			&i.SkippedCount,
			&i.ErroredCount,
			&i.CancelledCount,
			&i.DeviceKey,
			&i.DeviceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlowestResultsForRun = `-- name: ListSlowestResultsForRun :many
SELECT
    tr.id,
    tr.status,
    tr.duration_ms,
    tc.test_key,
    tc.name AS test_name,
    tc.suite
FROM
    test_results tr
    JOIN test_cases tc ON tc.id = tr.test_case_id
WHERE
    tr.run_id = ?1
    AND tr.duration_ms IS NOT NULL
ORDER BY
    tr.duration_ms DESC
LIMIT
    ?2
`

type ListSlowestResultsForRunParams struct {
	RunID       int64 `json:"run_id"`
	ResultLimit int64 `json:"result_limit"`
}

type ListSlowestResultsForRunRow struct {
	ID         int64          `json:"id"`
	Status     string         `json:"status"`
	DurationMs sql.NullInt64  `json:"duration_ms"`
	TestKey    string         `json:"test_key"`
	TestName   string         `json:"test_name"`
	Suite      sql.NullString `json:"suite"`
}

func (q *Queries) ListSlowestResultsForRun(ctx context.Context, arg ListSlowestResultsForRunParams) ([]ListSlowestResultsForRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listSlowestResultsForRun, arg.RunID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSlowestResultsForRunRow{}
	for rows.Next() {
		var i ListSlowestResultsForRunRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.DurationMs,
			&i.TestKey,
			&i.TestName,
			&i.Suite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
