// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_cases.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countResultsForRun = `-- name: CountResultsForRun :one
SELECT
    COUNT(*) AS total_count,
    COUNT(*) FILTER (
        WHERE
            STATUS = 'passed'
    ) AS passed_count,
    COUNT(*) FILTER (
        WHERE
            STATUS = 'failed'
    ) AS failed_count,
    COUNT(*) FILTER (
        WHERE
            STATUS = 'skipped'
    ) AS skipped_count,
    COUNT(*) FILTER (
        WHERE
            STATUS = 'error'
    ) AS errored_count,
    COUNT(*) FILTER (
        WHERE
            STATUS = 'cancelled'
    ) AS cancelled_count
FROM
    test_results
WHERE
    run_id = ?1
`

type CountResultsForRunRow struct {
	TotalCount     int64 `json:"total_count"`
	PassedCount    int64 `json:"passed_count"`
	FailedCount    int64 `json:"failed_count"`
	SkippedCount   int64 `json:"skipped_count"`
	ErroredCount   int64 `json:"errored_count"`
	CancelledCount int64 `json:"cancelled_count"`
}

func (q *Queries) CountResultsForRun(ctx context.Context, runID int64) (CountResultsForRunRow, error) {
	row := q.db.QueryRowContext(ctx, countResultsForRun, runID)
	var i CountResultsForRunRow
	err := row.Scan(
		&i.TotalCount,
		&i.PassedCount,
		&i.FailedCount,
		&i.SkippedCount,
		&i.ErroredCount,
		&i.CancelledCount,
	)
	return i, err
}

const createTestResult = `-- name: CreateTestResult :one
INSERT INTO
    test_results (
        run_id,
        test_case_id,
        attempt,
        STATUS,
        started_at,
        finished_at,
        duration_ms,
        message,
        failure_kind,
        failure_phase,
        failure_code,
        expected_value,
        actual_value,
        stack_trace,
        parameters_json,
        metrics_json,
        labels_json,
        details_json
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        ?11,
        ?12,
        ?13,
        ?14,
        ?15,
        ?16,
        ?17,
        ?18
    )
RETURNING
    id, run_id, test_case_id, attempt, status, started_at, finished_at, duration_ms, message, failure_kind, failure_phase, failure_code, expected_value, actual_value, stack_trace, parameters_json, metrics_json, labels_json, details_json
`

type CreateTestResultParams struct {
	RunID          int64          `json:"run_id"`
	TestCaseID     int64          `json:"test_case_id"`
	Attempt        int64          `json:"attempt"`
	Status         string         `json:"status"`
	StartedAt      sql.NullString `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	DurationMs     sql.NullInt64  `json:"duration_ms"`
	Message        sql.NullString `json:"message"`
	FailureKind    sql.NullString `json:"failure_kind"`
	FailurePhase   sql.NullString `json:"failure_phase"`
	FailureCode    sql.NullString `json:"failure_code"`
	ExpectedValue  sql.NullString `json:"expected_value"`
	ActualValue    sql.NullString `json:"actual_value"`
	StackTrace     sql.NullString `json:"stack_trace"`
	ParametersJson string         `json:"parameters_json"`
	MetricsJson    string         `json:"metrics_json"`
	LabelsJson     string         `json:"labels_json"`
	DetailsJson    string         `json:"details_json"`
}

func (q *Queries) CreateTestResult(ctx context.Context, arg CreateTestResultParams) (TestResult, error) {
	row := q.db.QueryRowContext(ctx, createTestResult,
		arg.RunID,
		arg.TestCaseID,
		arg.Attempt,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.Message,
		arg.FailureKind,
		arg.FailurePhase,
		arg.FailureCode,
		arg.ExpectedValue,
		arg.ActualValue,
		arg.StackTrace,
		arg.ParametersJson,
		arg.MetricsJson,
		arg.LabelsJson,
		arg.DetailsJson,
	)
	var i TestResult
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TestCaseID,
		&i.Attempt,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Message,
		&i.FailureKind,
		&i.FailurePhase,
		&i.FailureCode,
		&i.ExpectedValue,
		&i.ActualValue,
		&i.StackTrace,
		&i.ParametersJson,
		&i.MetricsJson,
		&i.LabelsJson,
		&i.DetailsJson,
	)
	return i, err
}

const filterTestResults = `-- name: FilterTestResults :many
SELECT
    tr.id,
    tr.status,
    tr.attempt,
    tr.duration_ms,
    tr.message,
    tr.failure_kind,
    tr.failure_code,
    tc.id AS test_case_id,
    tc.test_key,
    tc.name AS test_name,
    tc.suite,
    tc.result_kind,
    r.run_uid,
    r.commit_sha,
    r.branch,
    r.started_at,
    r.source_type,
    d.id AS device_id,
    d.device_key,
    d.display_name AS device_name
FROM
    test_results tr
    JOIN test_cases tc ON tc.id = tr.test_case_id
    JOIN runs r ON r.id = tr.run_id
    JOIN devices d ON d.id = r.device_id
WHERE
    r.project_id = ?1
    AND (
        ?2 IS NULL
        OR tr.status = ?2
    )
    AND (
        ?3 IS NULL
        OR r.device_id = ?3
    )
    AND (
        ?4 IS NULL
        OR r.branch = ?4
    )
    AND (
        ?5 IS NULL
        OR tc.test_key LIKE '%' || ?5 || '%'
        OR tc.name LIKE '%' || ?5 || '%'
    )
    AND (
        ?6 IS NULL
        OR tc.suite = ?6
    )
    AND (
        ?7 IS NULL
        OR r.commit_sha LIKE ?7 || '%'
    )
    AND (
        ?8 IS NULL
        OR tr.duration_ms >= ?8
    )
    AND (
        ?9 IS NULL
        OR r.started_at >= ?9
    )
    AND (
        ?10 IS NULL
        OR r.started_at < ?10
    )
ORDER BY
    r.started_at DESC,
    tr.id DESC
LIMIT
    ?12 OFFSET ?11
`

type FilterTestResultsParams struct {
	ProjectID     int64       `json:"project_id"`
	Status        interface{} `json:"status"`
	DeviceID      interface{} `json:"device_id"`
	Branch        interface{} `json:"branch"`
	TestSearch    interface{} `json:"test_search"`
	Suite         interface{} `json:"suite"`
	CommitPrefix  interface{} `json:"commit_prefix"`
	MinDurationMs interface{} `json:"min_duration_ms"`
	StartedFrom   interface{} `json:"started_from"`
	StartedUntil  interface{} `json:"started_until"`
	ResultOffset  int64       `json:"result_offset"`
	ResultLimit   int64       `json:"result_limit"`
}

type FilterTestResultsRow struct {
	ID          int64          `json:"id"`
	Status      string         `json:"status"`
	Attempt     int64          `json:"attempt"`
	DurationMs  sql.NullInt64  `json:"duration_ms"`
	Message     sql.NullString `json:"message"`
	FailureKind sql.NullString `json:"failure_kind"`
	FailureCode sql.NullString `json:"failure_code"`
	TestCaseID  int64          `json:"test_case_id"`
	TestKey     string         `json:"test_key"`
	TestName    string         `json:"test_name"`
	Suite       sql.NullString `json:"suite"`
	ResultKind  string         `json:"result_kind"`
	RunUid      string         `json:"run_uid"`
	CommitSha   string         `json:"commit_sha"`
	Branch      sql.NullString `json:"branch"`
	StartedAt   string         `json:"started_at"`
	SourceType  sql.NullString `json:"source_type"`
	DeviceID    int64          `json:"device_id"`
	DeviceKey   string         `json:"device_key"`
	DeviceName  sql.NullString `json:"device_name"`
}

func (q *Queries) FilterTestResults(ctx context.Context, arg FilterTestResultsParams) ([]FilterTestResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, filterTestResults,
		arg.ProjectID,
		arg.Status,
		arg.DeviceID,
		arg.Branch,
		arg.TestSearch,
		arg.Suite,
		arg.CommitPrefix,
		arg.MinDurationMs,
		arg.StartedFrom,
		arg.StartedUntil,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FilterTestResultsRow{}
	for rows.Next() {
		var i FilterTestResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Attempt,
			&i.DurationMs,
			&i.Message,
			&i.FailureKind,
			&i.FailureCode,
			&i.TestCaseID,
			&i.TestKey,
			&i.TestName,
			&i.Suite,
			&i.ResultKind,
			&i.RunUid,
			&i.CommitSha,
			&i.Branch,
			&i.StartedAt,
			&i.SourceType,
			&i.DeviceID,
			&i.DeviceKey,
			&i.DeviceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestResultForTestAndDevice = `-- name: GetLatestResultForTestAndDevice :one
SELECT
    tr.id, tr.run_id, tr.test_case_id, tr.attempt, tr.status, tr.started_at, tr.finished_at, tr.duration_ms, tr.message, tr.failure_kind, tr.failure_phase, tr.failure_code, tr.expected_value, tr.actual_value, tr.stack_trace, tr.parameters_json, tr.metrics_json, tr.labels_json, tr.details_json,
    r.run_uid,
    r.commit_sha,
    r.branch,
    r.started_at
FROM
    test_results tr
    JOIN runs r ON r.id = tr.run_id
WHERE
    tr.test_case_id = ?1
    AND r.device_id = ?2
ORDER BY
    r.started_at DESC,
    r.id DESC,
    tr.attempt DESC
LIMIT
    1
`

type GetLatestResultForTestAndDeviceParams struct {
	TestCaseID int64 `json:"test_case_id"`
	DeviceID   int64 `json:"device_id"`
}

type GetLatestResultForTestAndDeviceRow struct {
	ID             int64          `json:"id"`
	RunID          int64          `json:"run_id"`
	TestCaseID     int64          `json:"test_case_id"`
	Attempt        int64          `json:"attempt"`
	Status         string         `json:"status"`
	StartedAt      sql.NullString `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	DurationMs     sql.NullInt64  `json:"duration_ms"`
	Message        sql.NullString `json:"message"`
	FailureKind    sql.NullString `json:"failure_kind"`
	FailurePhase   sql.NullString `json:"failure_phase"`
	FailureCode    sql.NullString `json:"failure_code"`
	ExpectedValue  sql.NullString `json:"expected_value"`
	ActualValue    sql.NullString `json:"actual_value"`
	StackTrace     sql.NullString `json:"stack_trace"`
	ParametersJson string         `json:"parameters_json"`
	MetricsJson    string         `json:"metrics_json"`
	LabelsJson     string         `json:"labels_json"`
	DetailsJson    string         `json:"details_json"`
	RunUid         string         `json:"run_uid"`
	CommitSha      string         `json:"commit_sha"`
	Branch         sql.NullString `json:"branch"`
	StartedAt_2    string         `json:"started_at_2"`
}

func (q *Queries) GetLatestResultForTestAndDevice(ctx context.Context, arg GetLatestResultForTestAndDeviceParams) (GetLatestResultForTestAndDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestResultForTestAndDevice, arg.TestCaseID, arg.DeviceID)
	var i GetLatestResultForTestAndDeviceRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TestCaseID,
		&i.Attempt,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Message,
		&i.FailureKind,
		&i.FailurePhase,
		&i.FailureCode,
		&i.ExpectedValue,
		&i.ActualValue,
		&i.StackTrace,
		&i.ParametersJson,
		&i.MetricsJson,
		&i.LabelsJson,
		&i.DetailsJson,
		&i.RunUid,
		&i.CommitSha,
		&i.Branch,
		&i.StartedAt_2,
	)
	return i, err
}

const getTestResultByID = `-- name: GetTestResultByID :one
SELECT
    tr.id, tr.run_id, tr.test_case_id, tr.attempt, tr.status, tr.started_at, tr.finished_at, tr.duration_ms, tr.message, tr.failure_kind, tr.failure_phase, tr.failure_code, tr.expected_value, tr.actual_value, tr.stack_trace, tr.parameters_json, tr.metrics_json, tr.labels_json, tr.details_json,
    tc.test_key,
    tc.name AS test_name,
    tc.suite,
    tc.result_kind,
    tc.source_file,
    tc.source_symbol
FROM
    test_results tr
    JOIN test_cases tc ON tc.id = tr.test_case_id
WHERE
    tr.id = ?1
LIMIT
    1
`

type GetTestResultByIDRow struct {
	ID             int64          `json:"id"`
	RunID          int64          `json:"run_id"`
	TestCaseID     int64          `json:"test_case_id"`
	Attempt        int64          `json:"attempt"`
	Status         string         `json:"status"`
	StartedAt      sql.NullString `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	DurationMs     sql.NullInt64  `json:"duration_ms"`
	Message        sql.NullString `json:"message"`
	FailureKind    sql.NullString `json:"failure_kind"`
	FailurePhase   sql.NullString `json:"failure_phase"`
	FailureCode    sql.NullString `json:"failure_code"`
	ExpectedValue  sql.NullString `json:"expected_value"`
	ActualValue    sql.NullString `json:"actual_value"`
	StackTrace     sql.NullString `json:"stack_trace"`
	ParametersJson string         `json:"parameters_json"`
	MetricsJson    string         `json:"metrics_json"`
	LabelsJson     string         `json:"labels_json"`
	DetailsJson    string         `json:"details_json"`
	TestKey        string         `json:"test_key"`
	TestName       string         `json:"test_name"`
	Suite          sql.NullString `json:"suite"`
	ResultKind     string         `json:"result_kind"`
	SourceFile     sql.NullString `json:"source_file"`
	SourceSymbol   sql.NullString `json:"source_symbol"`
}

func (q *Queries) GetTestResultByID(ctx context.Context, id int64) (GetTestResultByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTestResultByID, id)
	var i GetTestResultByIDRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TestCaseID,
		&i.Attempt,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Message,
		&i.FailureKind,
		&i.FailurePhase,
		&i.FailureCode,
		&i.ExpectedValue,
		&i.ActualValue,
		&i.StackTrace,
		&i.ParametersJson,
		&i.MetricsJson,
		&i.LabelsJson,
		&i.DetailsJson,
		&i.TestKey,
		&i.TestName,
		&i.Suite,
		&i.ResultKind,
		&i.SourceFile,
		&i.SourceSymbol,
	)
	return i, err
}

const listFailuresForRun = `-- name: ListFailuresForRun :many
SELECT
    tr.id, tr.run_id, tr.test_case_id, tr.attempt, tr.status, tr.started_at, tr.finished_at, tr.duration_ms, tr.message, tr.failure_kind, tr.failure_phase, tr.failure_code, tr.expected_value, tr.actual_value, tr.stack_trace, tr.parameters_json, tr.metrics_json, tr.labels_json, tr.details_json,
    tc.test_key,
    tc.name AS test_name,
    tc.suite,
    tc.source_file,
    tc.source_symbol
FROM
    test_results tr
    JOIN test_cases tc ON tc.id = tr.test_case_id
WHERE
    tr.run_id = ?1
    AND tr.status IN ('failed', 'error')
ORDER BY
    CASE
        tr.status
        WHEN 'error' THEN 0
        ELSE 1
    END,
    tc.test_key,
    tr.attempt
`

type ListFailuresForRunRow struct {
	ID             int64          `json:"id"`
	RunID          int64          `json:"run_id"`
	TestCaseID     int64          `json:"test_case_id"`
	Attempt        int64          `json:"attempt"`
	Status         string         `json:"status"`
	StartedAt      sql.NullString `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	DurationMs     sql.NullInt64  `json:"duration_ms"`
	Message        sql.NullString `json:"message"`
	FailureKind    sql.NullString `json:"failure_kind"`
	FailurePhase   sql.NullString `json:"failure_phase"`
	FailureCode    sql.NullString `json:"failure_code"`
	ExpectedValue  sql.NullString `json:"expected_value"`
	ActualValue    sql.NullString `json:"actual_value"`
	StackTrace     sql.NullString `json:"stack_trace"`
	ParametersJson string         `json:"parameters_json"`
	MetricsJson    string         `json:"metrics_json"`
	LabelsJson     string         `json:"labels_json"`
	DetailsJson    string         `json:"details_json"`
	TestKey        string         `json:"test_key"`
	TestName       string         `json:"test_name"`
	Suite          sql.NullString `json:"suite"`
	SourceFile     sql.NullString `json:"source_file"`
	SourceSymbol   sql.NullString `json:"source_symbol"`
}

func (q *Queries) ListFailuresForRun(ctx context.Context, runID int64) ([]ListFailuresForRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listFailuresForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFailuresForRunRow{}
	for rows.Next() {
		var i ListFailuresForRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TestCaseID,
			&i.Attempt,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Message,
			&i.FailureKind,
			&i.FailurePhase,
			&i.FailureCode,
			&i.ExpectedValue,
			&i.ActualValue,
			&i.StackTrace,
			&i.ParametersJson,
			&i.MetricsJson,
			&i.LabelsJson,
			&i.DetailsJson,
			&i.TestKey,
			&i.TestName,
			&i.Suite,
			&i.SourceFile,
			&i.SourceSymbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResultsForRun = `-- name: ListResultsForRun :many
SELECT
    tr.id, tr.run_id, tr.test_case_id, tr.attempt, tr.status, tr.started_at, tr.finished_at, tr.duration_ms, tr.message, tr.failure_kind, tr.failure_phase, tr.failure_code, tr.expected_value, tr.actual_value, tr.stack_trace, tr.parameters_json, tr.metrics_json, tr.labels_json, tr.details_json,
    tc.test_key,
    tc.name AS test_name,
    tc.suite,
    tc.result_kind,
    tc.source_file,
    tc.source_symbol
FROM
    test_results tr
    JOIN test_cases tc ON tc.id = tr.test_case_id
WHERE
    tr.run_id = ?1
ORDER BY
    CASE
        tr.status
        WHEN 'error' THEN 0
        WHEN 'failed' THEN 1
        WHEN 'cancelled' THEN 2
        WHEN 'skipped' THEN 3
        WHEN 'passed' THEN 4
        ELSE 5
    END,
    tc.test_key,
    tr.attempt
`

type ListResultsForRunRow struct {
	ID             int64          `json:"id"`
	RunID          int64          `json:"run_id"`
	TestCaseID     int64          `json:"test_case_id"`
	Attempt        int64          `json:"attempt"`
	Status         string         `json:"status"`
	StartedAt      sql.NullString `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	DurationMs     sql.NullInt64  `json:"duration_ms"`
	Message        sql.NullString `json:"message"`
	FailureKind    sql.NullString `json:"failure_kind"`
	FailurePhase   sql.NullString `json:"failure_phase"`
	FailureCode    sql.NullString `json:"failure_code"`
	ExpectedValue  sql.NullString `json:"expected_value"`
	ActualValue    sql.NullString `json:"actual_value"`
	StackTrace     sql.NullString `json:"stack_trace"`
	ParametersJson string         `json:"parameters_json"`
	MetricsJson    string         `json:"metrics_json"`
	LabelsJson     string         `json:"labels_json"`
	DetailsJson    string         `json:"details_json"`
	TestKey        string         `json:"test_key"`
	TestName       string         `json:"test_name"`
	Suite          sql.NullString `json:"suite"`
	ResultKind     string         `json:"result_kind"`
	SourceFile     sql.NullString `json:"source_file"`
	SourceSymbol   sql.NullString `json:"source_symbol"`
}

func (q *Queries) ListResultsForRun(ctx context.Context, runID int64) ([]ListResultsForRunRow, error) {
	rows, err := q.db.QueryContext(ctx, listResultsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResultsForRunRow{}
	for rows.Next() {
		var i ListResultsForRunRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TestCaseID,
			&i.Attempt,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Message,
			&i.FailureKind,
			&i.FailurePhase,
			&i.FailureCode,
			&i.ExpectedValue,
			&i.ActualValue,
			&i.StackTrace,
			&i.ParametersJson,
			&i.MetricsJson,
			&i.LabelsJson,
			&i.DetailsJson,
			&i.TestKey,
			&i.TestName,
			&i.Suite,
			&i.ResultKind,
			&i.SourceFile,
			&i.SourceSymbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestHistory = `-- name: ListTestHistory :many
SELECT
    tr.id,
    tr.status,
    tr.attempt,
    tr.duration_ms,
    tr.message,
    tr.failure_kind,
    tr.failure_code,
    r.run_uid,
    r.commit_sha,
    r.branch,
    r.started_at,
    r.source_type,
    d.device_key,
    d.display_name AS device_name
FROM
    test_results tr
    JOIN runs r ON r.id = tr.run_id
    JOIN devices d ON d.id = r.device_id
WHERE
    tr.test_case_id = ?1
ORDER BY
    r.started_at DESC,
    r.id DESC,
    tr.attempt DESC
LIMIT
    ?3 OFFSET ?2
`

type ListTestHistoryParams struct {
	TestCaseID   int64 `json:"test_case_id"`
	ResultOffset int64 `json:"result_offset"`
	ResultLimit  int64 `json:"result_limit"`
}

type ListTestHistoryRow struct {
	ID          int64          `json:"id"`
	Status      string         `json:"status"`
	Attempt     int64          `json:"attempt"`
	DurationMs  sql.NullInt64  `json:"duration_ms"`
	Message     sql.NullString `json:"message"`
	FailureKind sql.NullString `json:"failure_kind"`
	FailureCode sql.NullString `json:"failure_code"`
	RunUid      string         `json:"run_uid"`
	CommitSha   string         `json:"commit_sha"`
	Branch      sql.NullString `json:"branch"`
	StartedAt   string         `json:"started_at"`
	SourceType  sql.NullString `json:"source_type"`
	DeviceKey   string         `json:"device_key"`
	DeviceName  sql.NullString `json:"device_name"`
}

func (q *Queries) ListTestHistory(ctx context.Context, arg ListTestHistoryParams) ([]ListTestHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestHistory, arg.TestCaseID, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestHistoryRow{}
	for rows.Next() {
		var i ListTestHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Attempt,
			&i.DurationMs,
			&i.Message,
			&i.FailureKind,
			&i.FailureCode,
			&i.RunUid,
			&i.CommitSha,
			&i.Branch,
			&i.StartedAt,
			&i.SourceType,
			&i.DeviceKey,
			&i.DeviceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestHistoryForDevice = `-- name: ListTestHistoryForDevice :many
SELECT
    tr.id,
    tr.status,
    tr.attempt,
    tr.duration_ms,
    tr.message,
    tr.failure_kind,
    tr.failure_code,
    r.run_uid,
    r.commit_sha,
    r.branch,
    r.started_at
FROM
    test_results tr
    JOIN runs r ON r.id = tr.run_id
WHERE
    tr.test_case_id = ?1
    AND r.device_id = ?2
ORDER BY
    r.started_at DESC,
    r.id DESC,
    tr.attempt DESC
LIMIT
    ?4 OFFSET ?3
`

type ListTestHistoryForDeviceParams struct {
	TestCaseID   int64 `json:"test_case_id"`
	DeviceID     int64 `json:"device_id"`
	ResultOffset int64 `json:"result_offset"`
	ResultLimit  int64 `json:"result_limit"`
}

type ListTestHistoryForDeviceRow struct {
	ID          int64          `json:"id"`
	Status      string         `json:"status"`
	Attempt     int64          `json:"attempt"`
	DurationMs  sql.NullInt64  `json:"duration_ms"`
	Message     sql.NullString `json:"message"`
	FailureKind sql.NullString `json:"failure_kind"`
	FailureCode sql.NullString `json:"failure_code"`
	RunUid      string         `json:"run_uid"`
	CommitSha   string         `json:"commit_sha"`
	Branch      sql.NullString `json:"branch"`
	StartedAt   string         `json:"started_at"`
}

func (q *Queries) ListTestHistoryForDevice(ctx context.Context, arg ListTestHistoryForDeviceParams) ([]ListTestHistoryForDeviceRow, error) {
	rows, err := q.db.QueryContext(ctx, listTestHistoryForDevice,
		arg.TestCaseID,
		arg.DeviceID,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestHistoryForDeviceRow{}
	for rows.Next() {
		var i ListTestHistoryForDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Attempt,
			&i.DurationMs,
			&i.Message,
			&i.FailureKind,
			&i.FailureCode,
			&i.RunUid,
			&i.CommitSha,
			&i.Branch,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTestCase = `-- name: UpsertTestCase :one
INSERT INTO
    test_cases (
        project_id,
        test_key,
        name,
        suite,
        result_kind,
        source_file,
        source_symbol,
        first_seen_at,
        last_seen_at
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9
    ) ON CONFLICT(project_id, test_key) DO
UPDATE
SET
    name = excluded.name,
    suite = excluded.suite,
    source_file = excluded.source_file,
    source_symbol = excluded.source_symbol,
    last_seen_at = excluded.last_seen_at
RETURNING
    id, project_id, test_key, name, suite, result_kind, source_file, source_symbol, first_seen_at, last_seen_at, metadata_json
`

type UpsertTestCaseParams struct {
	ProjectID    int64          `json:"project_id"`
	TestKey      string         `json:"test_key"`
	Name         string         `json:"name"`
	Suite        sql.NullString `json:"suite"`
	ResultKind   string         `json:"result_kind"`
	SourceFile   sql.NullString `json:"source_file"`
	SourceSymbol sql.NullString `json:"source_symbol"`
	FirstSeenAt  sql.NullString `json:"first_seen_at"`
	LastSeenAt   sql.NullString `json:"last_seen_at"`
}

func (q *Queries) UpsertTestCase(ctx context.Context, arg UpsertTestCaseParams) (TestCase, error) {
	row := q.db.QueryRowContext(ctx, upsertTestCase,
		arg.ProjectID,
		arg.TestKey,
		arg.Name,
		arg.Suite,
		arg.ResultKind,
		arg.SourceFile,
		arg.SourceSymbol,
		arg.FirstSeenAt,
		arg.LastSeenAt,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TestKey,
		&i.Name,
		&i.Suite,
		&i.ResultKind,
		&i.SourceFile,
		&i.SourceSymbol,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.MetadataJson,
	)
	return i, err
}

const upsertTestResult = `-- name: UpsertTestResult :one
INSERT INTO
    test_results (
        run_id,
        test_case_id,
        attempt,
        STATUS,
        started_at,
        finished_at,
        duration_ms,
        message,
        failure_kind,
        failure_phase,
        failure_code,
        expected_value,
        actual_value,
        stack_trace,
        parameters_json,
        metrics_json,
        labels_json,
        details_json
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8,
        ?9,
        ?10,
        ?11,
        ?12,
        ?13,
        ?14,
        ?15,
        ?16,
        ?17,
        ?18
    ) ON CONFLICT(run_id, test_case_id, attempt) DO
UPDATE
SET
    STATUS = excluded.status,
    started_at = excluded.started_at,
    finished_at = excluded.finished_at,
    duration_ms = excluded.duration_ms,
    message = excluded.message,
    failure_kind = excluded.failure_kind,
    failure_phase = excluded.failure_phase,
    failure_code = excluded.failure_code,
    expected_value = excluded.expected_value,
    actual_value = excluded.actual_value,
    stack_trace = excluded.stack_trace,
    parameters_json = excluded.parameters_json,
    metrics_json = excluded.metrics_json,
    labels_json = excluded.labels_json,
    details_json = excluded.details_json
RETURNING
    id, run_id, test_case_id, attempt, status, started_at, finished_at, duration_ms, message, failure_kind, failure_phase, failure_code, expected_value, actual_value, stack_trace, parameters_json, metrics_json, labels_json, details_json
`

type UpsertTestResultParams struct {
	RunID          int64          `json:"run_id"`
	TestCaseID     int64          `json:"test_case_id"`
	Attempt        int64          `json:"attempt"`
	Status         string         `json:"status"`
	StartedAt      sql.NullString `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	DurationMs     sql.NullInt64  `json:"duration_ms"`
	Message        sql.NullString `json:"message"`
	FailureKind    sql.NullString `json:"failure_kind"`
	FailurePhase   sql.NullString `json:"failure_phase"`
	FailureCode    sql.NullString `json:"failure_code"`
	ExpectedValue  sql.NullString `json:"expected_value"`
	ActualValue    sql.NullString `json:"actual_value"`
	StackTrace     sql.NullString `json:"stack_trace"`
	ParametersJson string         `json:"parameters_json"`
	MetricsJson    string         `json:"metrics_json"`
	LabelsJson     string         `json:"labels_json"`
	DetailsJson    string         `json:"details_json"`
}

// Useful if an importer retry can encounter already inserted rows
// within an otherwise incomplete run.
func (q *Queries) UpsertTestResult(ctx context.Context, arg UpsertTestResultParams) (TestResult, error) {
	row := q.db.QueryRowContext(ctx, upsertTestResult,
		arg.RunID,
		arg.TestCaseID,
		arg.Attempt,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.Message,
		arg.FailureKind,
		arg.FailurePhase,
		arg.FailureCode,
		arg.ExpectedValue,
		arg.ActualValue,
		arg.StackTrace,
		arg.ParametersJson,
		arg.MetricsJson,
		arg.LabelsJson,
		arg.DetailsJson,
	)
	var i TestResult
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TestCaseID,
		&i.Attempt,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Message,
		&i.FailureKind,
		&i.FailurePhase,
		&i.FailureCode,
		&i.ExpectedValue,
		&i.ActualValue,
		&i.StackTrace,
		&i.ParametersJson,
		&i.MetricsJson,
		&i.LabelsJson,
		&i.DetailsJson,
	)
	return i, err
}
