when:
  - event: push
    branch: master
  - event: pull_request
  - event: manual

steps:
  test:
    image: nixos/nix
    commands:
      - nix develop .#ci --extra-experimental-features "nix-command flakes" -c go test ./...
      - nix develop .#ci --extra-experimental-features "nix-command flakes" -c go build ./cmd/tethux
