when:
  - event: manual
  - event: push
    branch: master

labels:
  host: nas

depends_on:
  - checks

steps:
  deploy-ci-results-viewer:
    image: nixos/nix
    pull: false
    volumes:
      - tethux-ci-nix:/nix
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/cache/tethux-ci:/var/cache/tethux-ci
      - /Containers/homelab/tethux-ci-viewer:/deployment
    commands:
      - nix develop .#ci --extra-experimental-features "nix-command flakes" -c go run ./tools/ci deploy viewer --source . --data-dir /var/cache/tethux-ci/viewer --env-file /deployment/.env
