when:
  - event: push
  - event: pull_request
  - event: manual

labels:
  host: nas
  tethux-test-host: "true"
  privileged: "true"

steps:
  docker-bridge-and-all-providers:
    image: nixos/nix
    pull: false
    environment:
      TETHUX_TEST_ARCHIVE_ROOT: /var/lib/tethux-ci/archive
    volumes:
      - tethux-ci-nix:/nix
      - /root/.ssh:/root/.ssh:ro
      - /var/cache/tethux-ci/go-build:/root/.cache/go-build
      - /var/cache/tethux-ci/go-mod:/root/go/pkg/mod
      - /var/cache/tethux-ci/archive:/var/lib/tethux-ci/archive
    commands:
      - nix develop .#ci --extra-experimental-features "nix-command flakes" -c go run ./tools/ci run remote-laptop --host ci@10.0.0.100 --runtime docker --archive --device laptop-100
