when:
  - event: push
  - event: pull_request
  - event: manual

labels:
  host: nas
  tethux-test-host: "true"
  privileged: "true"

depends_on:
  - laptop-100

steps:
  podman-bridge-and-all-providers:
    image: nixos/nix
    pull: false
    environment:
      XDG_CONFIG_HOME: /woodpecker/src/github.com/tethux/tethux/.config
      OTEL_EXPORTER_OTLP_ENDPOINT: http://10.0.0.21:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_EXPORTER_OTLP_INSECURE: "true"
      OTEL_RESOURCE_ATTRIBUTES: service.name=tethux-ci,ci.pipeline=laptop-78
    volumes:
      - tethux-ci-nix:/nix
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - /root/.ssh/known_hosts:/root/.ssh/known_hosts
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - export OTEL_RESOURCE_ATTRIBUTES="service.name=tethux-ci,ci.pipeline=$CI_PIPELINE_NAME,ci.repository=$CI_REPO,ci.commit=$CI_COMMIT_SHA,ci.run.url=$CI_PIPELINE_URL"
      - export DAGGER_TRACE_NAME="$CI_REPO_NAME:$CI_PIPELINE_NAME:$CI_COMMIT_SHA"
      - nix develop .#ci --extra-experimental-features "nix-command flakes" -c dagger call laptop-78 --source=. --ssh-key=file:/root/.ssh/id_rsa --known-hosts=file:/root/.ssh/known_hosts
