when:
  - event: push
  - event: pull_request
  - event: manual

labels:
  host: nas
  tethux-canary: "true"
  privileged: "true"

steps:
  lint-test-build-and-nix:
    image: nixos/nix
    pull: false
    volumes:
      - tethux-ci-nix:/nix
      - /var/cache/tethux-ci/go-build:/root/.cache/go-build
      - /var/cache/tethux-ci/go-mod:/root/go/pkg/mod
      - /var/cache/tethux-ci/archive:/var/lib/tethux-ci/archive
    commands:
      - nix develop .#ci --extra-experimental-features "nix-command flakes" -c env TETHUX_DEVICE_ID=nas-runner-1 ./nix/scripts/test-archive-run.sh normal ./nix/scripts/normal-ci.sh
