when:
  - event: push
  - event: pull_request
  - event: manual

labels:
  host: nas
  tethux-canary: "true"
  privileged: "true"

steps:
  lint-test-build-and-nix:
    image: nixos/nix
    volumes:
      - /var/cache/tethux-ci/nix:/nix
      - /var/cache/tethux-ci/go-build:/root/.cache/go-build
      - /var/cache/tethux-ci/go-mod:/root/go/pkg/mod
    commands:
      - nix develop .#ci --extra-experimental-features "nix-command flakes" -c golangci-lint run -c .golangci.yml
      - nix develop .#ci --extra-experimental-features "nix-command flakes" -c sh -c 'go test ./... -json | tee go-test.jsonl'
      - nix develop .#ci --extra-experimental-features "nix-command flakes" -c go build ./cmd/tethux
      - nix eval .#nixosConfigurations.canary-10-0-0-100.config.system.build.toplevel.drvPath --extra-experimental-features "nix-command flakes"
      - nix eval .#nixosConfigurations.canary-former-10-0-0-12.config.system.build.toplevel.drvPath --extra-experimental-features "nix-command flakes"
      - nix build .#checks.x86_64-linux.unit .#checks.x86_64-linux.build --extra-experimental-features "nix-command flakes"
